import logging
import re, os
from fparser.two.utils import walk
from fparser.two import Fortran2003 as F23
from fparser.two import Fortran2008 as F28
from fparser.common.readfortran import FortranFileReader, FortranStringReader
from fparser.two.parser import ParserFactory
from collections import deque
from line_length import FortLineLength 

class Processor:
    """
    A class for parsing Fortran files, strings, and statements using fparser, 
    creating Abstract Syntax Trees (ASTs), generating Fortran code, and performing 
    various mappings.

    Attributes:
    -----------
    parser : object
        An instance of the Fortran 2008 parser created by fparser.
    """
    def __init__(self):
        logging.basicConfig(level=logging.INFO)
        self.parser = ParserFactory().create(std="f2008")
        self.line_length = FortLineLength()
        current_dir = os.getcwd()
        self.benchmark_dir = os.path.join(current_dir, 'benchmark')
        os.makedirs(self.benchmark_dir, exist_ok=True)

    def parse_fortran_file(self, file_path):
        """
        Parses a Fortran source file and returns its Abstract Syntax Tree (AST).

        Parameters:
        -----------
        file_path : str
            Path to the Fortran source file to be parsed.

        Returns:
        --------
        parse_tree : fparser.two.Fortran2008.Program
            The root of the abstract syntax tree (AST) generated by fparser.

        Raises:
        -------
        Exception
            If parsing fails due to invalid syntax or I/O issues.
        """
        try:
            reader = FortranFileReader(file_path, ignore_comments=False)
            parse_tree = self.parser(reader)
            logging.info(f"Successfully parsed file: {file_path}")
            return parse_tree
        except Exception as e:
            logging.error(f"Failed to parse file: {file_path}, Error: {e}")
            raise

    def parse_fortran_string(self, string):
        """
        Parses a Fortran code snippet provided as a string and returns its AST.

        Parameters:
        -----------
        string : str
            A string containing valid Fortran source code.

        Returns:
        --------
        parse_tree : fparser.two.Fortran2008.Program
            The root of the AST representing the parsed code.

        Raises:
        -------
        Exception
            If the parsing fails due to invalid syntax or other errors.
        """
        try:
            reader = FortranStringReader(string, ignore_comments=False)
            parse_tree = self.parser(reader)
            logging.info(f"Successfully parsed string!")
            return parse_tree
        except Exception as e:
            logging.error(f"Failed to parse string, Error: {e}")
            raise

    def parse_fortran_statement(self, stmt_str):
        """
        Parses a single Fortran statement and returns its corresponding fparser AST node.

        Parameters:
        -----------
        stmt_str : str
            A single line or statement of Fortran code (e.g., an assignment, loop, etc.).

        Returns:
        --------
        node : fparser.two.base.Base
            The fparser AST node representing the parsed statement.

        Notes:
        ------
        - Wraps the statement inside a dummy program (with `program foo ... end`) to ensure it's valid Fortran.
        - This approach allows fparser to treat the input as a complete unit for parsing.
        - Filters out the program start and end lines to return only the actual statement node.
        - Useful for identifying what kind of AST node a statement maps to in `fparser.two.Fortran2003`.

        Raises:
        -------
        Exception
            If the statement cannot be parsed.
        """
        code = f"""
          program foo
          {stmt_str}
          end
        """
        try:
            reader = FortranStringReader(code, ignore_comments=True)
            parse_tree = self.parser(reader)
            for node in parse_tree.children:
                for child in node.content:
                    if not isinstance(child, F23.Program_Stmt) and not isinstance(child, F23.End_Program_Stmt):
                        logging.info(f"Successfully parsed statement: {stmt_str}")
                        return child
            logging.warning(f"No valid statements found in: {stmt_str}")
            return None
        except Exception as e:
            logging.error(f"Failed to parse statement: {stmt_str}, Error: {e}")
            raise

    def parse_fortran_comment(self, stmt_str):
        """
        Parses a Fortran comment and returns the corresponding fparser comment node.

        Parameters:
        -----------
        stmt_str : str
            A single line Fortran comment (e.g., '! this is a comment').

        Returns:
        --------
        node : fparser.two.utils.Comment
            The fparser AST node representing the comment.

        Notes:
        ------
        - The comment is wrapped in a dummy program block for parsing context.
        - `ignore_comments=False` is required to ensure comments are preserved.
        - Walks the parsed tree to extract the comment node.
        - If no valid comment node is found, it raises a runtime error.

        Raises:
        -------
        RuntimeError
            If the comment could not be parsed or extracted.
        """
        code = f"""
    program foo
    {stmt_str}
    end
    """
        try:
            reader = FortranStringReader(code, ignore_comments=False)
            parse_tree = self.parser(reader)
            for node in parse_tree.children:
                if not hasattr(node, 'content'):
                    continue
                for child in node.content:
                    if not isinstance(child, F23.Program_Stmt) and not isinstance(child, F23.End_Program_Stmt):
                        return child.children[0].children[0]
        except Exception as e:
            raise RuntimeError(f"An error occurred while parsing Fortran code: {e}")

    def initiate_empty_routine(self, subroutine_name):
        """
        Generates a dummy Fortran subroutine with an open statement and a print,
        then parses and returns its AST node.

        Parameters:
        -----------
        subroutine_name : str
            The name to be used in the dummy subroutine's printed message and file path.

        Returns:
        --------
        subroutine_node : fparser.two.Fortran2003.Subroutine_Subprogram
            The root AST node representing the generated subroutine.

        Notes:
        ------
        - The dummy subroutine includes:
            - An `open` statement opening a binary file.
            - A write (print) statement to indicate execution.
        - The file path is constructed using `self.benchmark_dir` and the subroutine name.
        - Useful as a placeholder routine during transformation or benchmarking.
        - Parses the generated code using `FortranStringReader` and returns the subroutine AST node.
    
        Raises:
        -------
        Exception
            If the subroutine code cannot be parsed.
        """
        try:
            code_template = f"""
            subroutine read_dummy()
                open(unit=1363, file='{self.benchmark_dir}/{subroutine_name}/dummy.bin', form='unformatted', status='old')
                write(*,*) '--- inside the read dummy routine for {subroutine_name} ---'
            end subroutine read_dummy
            """
            reader = FortranStringReader(code_template, ignore_comments=True)
            parse_tree = self.parser(reader)
            return parse_tree.children[0]
        except Exception as e:
            logging.error(f"Failed to generate Fortran code for routine {subroutine_name}, Error: {e}")
            raise

    def separate_entity_declarations(self, declaration_stmt):
        """
        Splits a combined Fortran type declaration statement into separate declarations,
        one for each variable.

        Parameters:
        -----------
        declaration_stmt : fparser.two.Fortran2003.Type_Declaration_Stmt
            A parsed Fortran declaration statement, possibly declaring multiple variables.

        Returns:
        --------
        new_decl : list of fparser.two.Fortran2003.Type_Declaration_Stmt
            A list of declaration statements, each declaring exactly one variable.

        Notes:
        ------
        - Preserves the left part (type, kind, dimension, intent, etc.).
        - Separates the variable names to create one declaration per variable.
        - Useful in code transformations that require granular control of declarations.
        """
        try:
            left_part = []
            right_part = []
            for child in declaration_stmt.children:
                if child==None:
                    continue
                if not isinstance(child, F23.Entity_Decl_List):
                    left_part.append(child.tostr())
                if isinstance(child, F23.Entity_Decl_List):
                    for child_child in walk(child, F23.Entity_Decl):
                        right_part.append(child_child.string)

            left_part_merged = ', '.join([name for name in left_part])
            new_decl = []
            for variable in right_part:
                decl = f"{left_part_merged} :: {variable}"
                new_decl.append(F23.Type_Declaration_Stmt(decl))
            return new_decl
        except Exception as e:
            print(f"An error occurred during separation of variables: {e}")
            return None

    def add_entity_to_declaration(self, declaration_stmt, var_modif):
        """
        Modifies a Fortran declaration by appending new variables (with _copy suffix)
        for those listed in var_modif.

        Parameters:
        -----------
        declaration_stmt : fparser.two.Fortran2003.Type_Declaration_Stmt
            The original Fortran declaration statement.

        var_modif : list of str
            A list of variable names for which new suffixed variables should be added.

        Returns:
        --------
        new_decl : fparser.two.Fortran2003.Type_Declaration_Stmt
            A new declaration statement including the original and modified variables.

        Notes:
        ------
        - Preserves the left-hand part (e.g., REAL(KIND=f64), INTENT(OUT)).
        - Duplicates any variable found in var_modif, adding a _copy version.
        - Useful for creating CPU/GPU variants of variables in transformed code.
        """
        try:
            left_part = []
            right_part = []
            for child in declaration_stmt.children:
                if child==None:
                    continue
                if not isinstance(child, F23.Entity_Decl_List):
                    left_part.append(child.tostr())
                if isinstance(child, F23.Entity_Decl_List):
                    for child_child in walk(child, F23.Entity_Decl):
                        right_part.append(child_child.string)
                        if child_child.string in var_modif:
                            right_part.append(child_child.string+'_copy')

            left_part_merged = ', '.join([name for name in left_part])
            right_part_merged = ', '.join([name for name in right_part])
            decl = f"{left_part_merged} :: {right_part_merged}"
            new_decl = F23.Type_Declaration_Stmt(decl)
            return new_decl
        except Exception as e:
            print(f"An error occurred during adding an entity to a declaration: {e}")
            return None

    def separate_entity_allocation(self, allocate_stmt):
        """
        Separates a compound Fortran ALLOCATE statement into multiple individual allocate statements,
        one for each variable.

        Parameters:
        -----------
        allocate_stmt : fparser.two.Fortran2003.Allocate_Stmt
            A parsed allocate statement, potentially allocating multiple variables.

        Returns:
        --------
        new_allocation : list of fparser.two.Fortran2003.Allocate_Stmt
            A list of new allocate statements, each allocating a single variable.

        Notes:
        ------
        - Also preserves optional allocation options (e.g., `stat=istat`).
        - Supports both Fortran 2003 and Fortran 2008 AST types.
        - Useful when tools need one allocation per line for readability or instrumentation.

        Raises:
        -------
        Exception
            If parsing or transformation fails.
        """
        try:
            lst = []
            opt = None

            for child in allocate_stmt.children:
                if child is None:
                    continue
                if isinstance(child, F23.Allocation_List) or isinstance(child, F28.Allocation_List):
                    for grandchild in child.children:
                        lst.append(grandchild.tostr())
                elif isinstance(child, F23.Alloc_Opt_List) or isinstance(child, F28.Alloc_Opt_List):
                    for grandchild in child.children:
                        opt = grandchild.tostr()

            new_allocation = []
            for variable in lst:
                if opt is not None:                                                                                                              
                    allocation = f"allocate({variable}, {opt})"                                      
                else:                                                                                  
                    allocation = f"allocate({variable})"   

                new_allocation.append(F23.Allocate_Stmt(allocation))

            logging.info("Successfully generated allocation statements")
            return new_allocation

        except Exception as e:
            logging.error(f"Failed to generate allocation statements, Error: {e}")
            raise

    def add_entity_to_allocation(self, allocate_stmt, var_modif, openacc=False):
        """
        Wraps allocation statements with `.not. allocated(...)` condition and adds
        suffixed allocations (e.g., `_copy`) for variables in var_modif.

        Parameters:
        -----------
        allocate_stmt : fparser.two.Fortran2003.Allocate_Stmt
            A parsed allocate statement, potentially allocating multiple variables.

        var_modif : list of str
            A list of variable names that require shadow allocation (e.g., with '_copy' suffix).

        Returns:
        --------
        new_allocation : list of fparser.two.statements.If_Construct
            A list of AST nodes, each wrapping allocation in a conditional check.

        Notes:
        ------
        - Wraps each allocation inside an `if (.not. allocated(...)) then` block.
        - If variable is in var_modif, creates a duplicate allocation for `<var>_copy`.
        - Prevents redundant allocations at runtime and supports CPU/GPU memory handling.

        Raises:
        -------
        Exception
            If generation or parsing of statements fails.
        """
        try:
            new_allocation = []
            for child in allocate_stmt.children:
                if child is None:
                    continue
                if isinstance(child, F23.Allocation_List) or isinstance(child, F28.Allocation_List):
                    for grandchild in child.children:
                        allocate_name = grandchild.children[0].tostr()
                        code = f"if(.not. allocated({allocate_name}))then\n{allocate_stmt.tostr()}\nend if"
                        new_allocation.append(self.parse_fortran_statement(code))
                        if allocate_name in var_modif:
                            if openacc:
                                allocate_name_add = allocate_name + '_copy'
                                allocation = re.sub(rf'\b{allocate_name}\b', allocate_name_add, allocate_stmt.tostr())
                                code = f"if(.not. allocated({allocate_name_add}))then\n{allocation}\nend if"
                                new_allocation.append(self.parse_fortran_statement(code))
            logging.info("Successfully generated allocation statements")
            return new_allocation
        except Exception as e:
            logging.error(f"Failed to generate allocation statements, Error: {e}")
            raise

    def map_declaration(self, implicit_dec, explicit_dec=None, dimensions=None):
        """
        Maps an assumed-shape or partially defined Fortran declaration (e.g. DIMENSION(:))
        to a fully explicit declaration (e.g. DIMENSION(kjpindex)).

        Parameters:
        -----------
        implicit_dec : fparser.two.Fortran2003.Type_Declaration_Stmt
            The original implicit declaration, typically with DIMENSION(:) or missing shape info.

        explicit_dec : fparser.two.Fortran2003.Type_Declaration_Stmt, optional
            A full declaration used to infer shape (when `dimensions` is not explicitly given).

        dimensions : str, optional
            A comma-separated string of dimensions (e.g. "kjpindex, nlev") to override shape detection.

        Returns:
        --------
        parsed_decl : fparser.two.Fortran2003.Type_Declaration_Stmt
            A new, fully formed declaration statement with mapped shape.

        Raises:
        -------
        ValueError if the variable type, name, or shape are missing or cannot be inferred.
        Exception if parsing the constructed declaration fails.
        """
        try:
            if walk(implicit_dec, F23.Intrinsic_Type_Spec):
                type_and_attributes = walk(implicit_dec, F23.Intrinsic_Type_Spec)[0].tostr()
            else:
                raise ValueError("variable type is not present!")
            
            if walk(implicit_dec, F23.Entity_Decl):
                array_name = walk(implicit_dec, F23.Entity_Decl)[0].tostr()
            else:
                raise ValueError("variable name is not present!")
            
            if dimensions is None:
                assert explicit_dec is not None, "explicit_dec must be provided when assumed_shape is not None."
                if walk(explicit_dec, F23.Explicit_Shape_Spec):
                    shape = []
                    for dim in walk(explicit_dec, F23.Explicit_Shape_Spec):
                        shape.append(dim.tostr())
                    dimensions = ', '.join([name for name in shape])
                else:
                    raise ValueError("array shape is not present!")
            
            if walk(implicit_dec, F23.Intent_Attr_Spec):
                intent_attr = walk(implicit_dec, F23.Intent_Attr_Spec)[0].tostr()
                new_decl = f"{type_and_attributes}, DIMENSION({dimensions}), {intent_attr} :: {array_name}"
            else:
                new_decl = f"{type_and_attributes}, DIMENSION({dimensions}) :: {array_name}"
            
            logging.info(f"Mapped declaration: {new_decl}")
            parsed_decl = F23.Type_Declaration_Stmt(new_decl)
            return parsed_decl
        except Exception as e:
            logging.error(f"Failed to map declaration, Error: {e}")
            raise

    def combine_allocate_declaration(self, variable_declarations):
        """
        Combines a type declaration and an ALLOCATE statement into a single, explicit
        Fortran declaration with fixed dimensions.

        Parameters:
        -----------
        variable_declarations : list
            A list of two AST nodes: one must be a Type_Declaration_Stmt,
            the other an Allocate_Stmt.

        Returns:
        --------
        parsed_decl : fparser.two.Fortran2003.Type_Declaration_Stmt
            A combined type declaration statement with explicit shape.

        Raises:
        -------
        ValueError
            If shape or type/name information cannot be extracted.
        """
        try:
            for item in variable_declarations:
                if isinstance(item, F23.Allocate_Stmt):
                    if walk(item, F23.Allocate_Shape_Spec):
                        shape = []
                        for dim in walk(item, F23.Allocate_Shape_Spec):
                            shape.append(dim.tostr())
                        dimensions = ', '.join([name for name in shape])
                    else:
                        raise ValueError("allocarion shape is not present!")
                elif isinstance(item, F23.Type_Declaration_Stmt):
                    if walk(item, F23.Intrinsic_Type_Spec):
                        type_and_attributes = walk(item, F23.Intrinsic_Type_Spec)[0].tostr()
                    else:
                        raise ValueError("variable type is not present!")
                    if walk(item, F23.Entity_Decl):
                        array_name = walk(item, F23.Entity_Decl)[0].tostr()
                    else:
                        raise ValueError("variable name is not present!")
                else:
                    raise ValueError('Unrecognized statement')
            
            combined_statement = f"{type_and_attributes}, DIMENSION({dimensions}) :: {array_name}"
            logging.info(f"Combined statement: {combined_statement}")
            parsed_decl = F23.Type_Declaration_Stmt(combined_statement)
            return parsed_decl
        except Exception as e:
            logging.error(f"Failed to combine allocate and declaration, Error: {e}")
            raise

    def remove_intent_and_save(self, type_declaration_stmts):
        """
        Removes specific Fortran attributes such as INTENT, SAVE, and PUBLIC 
        from a list of type declaration statements.

        Parameters:
        -----------
        type_declaration_stmts : list of Fortran2003.Type_Declaration_Stmt
            A list of Fortran type declaration AST nodes to clean.

        Returns:
        --------
        cleaned_statements : list of Fortran2003.Type_Declaration_Stmt
            Modified declarations without INTENT, SAVE, or PUBLIC attributes.

        Notes:
        ------
        - Useful for extracting variable declarations from subroutines and 
        reusing them in contexts where INTENT or SAVE is not allowed.
        - Maintains DIMENSION, POINTER, ALLOCATABLE, and other attributes.
        - Skips any node that is not a Type_Declaration_Stmt.
        """
        exclude = ['SAVE', 'INTENT', 'PUBLIC']
        cleaned_statements = []
        try:
            for stmt in type_declaration_stmts:
                if not isinstance(stmt, F23.Type_Declaration_Stmt):
                    cleaned_statements.append(stmt)
                    continue
                left_part = []
                right_part = ""
                for child in stmt.children:
                    if isinstance(child, F23.Intrinsic_Type_Spec):
                        left_part.append(child.tostr())
                    elif isinstance(child, F28.Attr_Spec_List) or isinstance(child, F23.Attr_Spec_List):
                        for grandchild in child.children:
                            if not any(excl in grandchild.string for excl in exclude):
                                left_part.append(grandchild.tostr())
                    elif isinstance(child, F23.Entity_Decl_List):
                        right_part = child.tostr()

                left_part_merged = ', '.join(left_part)
                cleaned_stmt_str = f"{left_part_merged} :: {right_part}"
                cleaned_stmt = F23.Type_Declaration_Stmt(cleaned_stmt_str)
                cleaned_statements.append(cleaned_stmt)
            logging.info("Successfully removed INTENT and SAVE attributes from statements")
            return cleaned_statements
        except Exception as e:
            logging.error(f"Failed to remove INTENT and SAVE attributes, Error: {e}")
            raise

    def out_module_fortran(self, subroutine_name):
        """
        Generates and parses a Fortran `module` containing globally defined 
        constants, variables, and a utility subroutine for initialization.

        This method programmatically creates a Fortran source code string that 
        defines:

        - A module named `module_global`
        - Parameter constants (e.g., `i_std`, `r_std`, array sizes)
        - Globally scoped scalar variables
        - A `declaration_initialization` subroutine that opens a binary file 
            associated with the given `subroutine_name`

        Parameters:
        -----------
        subroutine_name : str
            Name of the subroutine for which the global binary file path 
            is constructed. This name is inserted into the `OPEN` statement 
            to load `global.bin`.

        Returns:
        --------
        parse_tree : fparser.two.Fortran2003.Program
            The parsed AST representation of the module and its contents.

        Raises:
        -------
        Exception
            If the Fortran string fails to parse.

        Notes:
        ------
        This method is useful for generating boilerplate global Fortran modules 
        used in benchmarking, testing, or modular code generation. It ensures 
        consistency in parameters and supports I/O operations embedded within 
        global modules.
        """
        code = f"""
        module module_global
        implicit none
        integer, parameter :: i_std = 4
        integer, parameter :: r_std = 8
        integer(kind = i_std), parameter :: nsnow=3
        integer(kind = i_std), parameter :: nslm=11
        integer(kind = i_std), parameter :: nvm = 15
        integer(kind = i_std), parameter :: nstm = 3
        integer(kind = i_std), parameter :: kjpindex = 4717
        integer                          :: ier
        integer(kind = i_std)            :: ic0, ic
        real(kind = r_std)               :: icr, start_time, stop_time
        contains
        subroutine declaration_initialization()
        open(unit=1363, file='{self.benchmark_dir}/{subroutine_name}/global.bin', form='unformatted', status='old')
        write(*,*)'--- add the declaration and initialization in module global ---'
        end subroutine declaration_initialization
        end module module_global
        """
        try:
            reader = FortranStringReader(code, ignore_comments=False)
            parse_tree = self.parser(reader)
            logging.info("Successfully parsed module code")
            return parse_tree
        except Exception as e:
            logging.error(f"Failed to parse module code, Error: {e}")
            raise

    def check_point(self, var, var_copy, info):
        """
        Generates and parses a Fortran `IF` block that performs a runtime check 
        to compare two variables: typically a GPU version and a CPU reference.

        The generated code compares either scalar or array variables using `.EQ.` 
        or `.EQV.` (for logical types), and provides diagnostic output if the 
        check fails — including max errors or mismatched values.

        Parameters:
        -----------
        var : str
            The name of the GPU or test version of the variable (e.g., 'a').
    
        var_copy : str
            The name of the CPU or reference version of the variable (e.g., 'a_copy').
    
        info : list of str
            A list of type/property descriptors, such as ['REAL', 'DIMENSION'] 
            or ['LOGICAL'], which guides the comparison logic:
        
            - If 'DIMENSION' is present, array comparison is used (with `ALL(...)`)
            - If 'LOGICAL' is present, `.EQV.` is used instead of `.EQ.`
            - Otherwise, scalar `.EQ.` comparison is performed

        Returns:
        --------
        code : fparser.two.Fortran2003.If_Construct
            The parsed AST of the generated Fortran comparison block.

        Notes:
        ------
        - Supports scalar and array types.
        - Supports LOGICAL and numeric comparisons.
        - Designed for automated testing or benchmarking frameworks to validate
            GPU/CPU equivalence.
        - Diagnostic printouts help locate mismatch severity and range.
        """
        code = ""

        if 'DIMENSION' in info:
            if 'LOGICAL' not in info:
                code_template = f"""
                IF (ALL({var} .EQ. {var_copy})) THEN
                    write(*,*) 'Test passed: All elements in {var}_comp are equal to {var_copy}.'
                ELSE
                    write(*,*) ''
                    write(*,*) 'Test failed: All elements in {var}_comp do not match {var_copy}.'
                    write(*,'(A, E25.16)') 'Maximum absolute error:',  maxval(abs({var} - {var_copy}))
                    write(*,'(A, 2E25.16)') 'Min and Max of {var}_comp:', minval({var}), maxval({var})
                    write(*,'(A, 2E25.16)') 'Min and Max of {var_copy}:', minval({var_copy}), maxval({var_copy})
                    write(*,*) ''
                ENDIF
                """
            else:
                code_template = f"""
                IF (ALL({var} .EQV. {var_copy})) THEN
                    write(*,*) 'LOGICAL EQV test passed: All elements in {var}_comp are equal to {var_copy}.'
                ELSE
                    write(*,*) ''
                    write(*,*) 'LOGICAL EQV test failed: Not all elements in {var}_comp match {var_copy}.'
                    write(*,*) ''
                ENDIF
                """
        else:
            if 'LOGICAL' not in info:
                code_template = f"""
                IF ({var} .EQ. {var_copy}) THEN
                    write(*,*) 'Test passed: {var}_comp is equal to {var_copy}.'
                ELSE
                    write(*,*) ''
                    write(*,*) 'Test failed: {var}_comp does not match {var_copy}.'
                    write(*,'(A, E25.16)') 'Absolute error:', abs({var} - {var_copy})
                    write(*,'(A, 2E25.16)') '{var}_comp:', {var}
                    write(*,'(A, 2E25.16)') '{var_copy}:', {var_copy}
                    write(*,*) ''
                ENDIF
                """
            else:
                code_template = f"""
                IF ({var} .EQV. {var_copy}) THEN
                    write(*,*) 'LOGICAL EQV test passed: {var}_comp is equal to {var_copy}.'
                ELSE
                    write(*,*) ''
                    write(*,*) 'LOGICAL EQV test failed: {var}_comp does not match {var_copy}.'
                    write(*,'(A, L1)') '{var}_comp:', {var}
                    write(*,'(A, L1)') '{var_copy}:', {var_copy}
                    write(*,*) ''
                ENDIF
                """
        code = self.parse_fortran_statement(code_template)

        return code

    def out_main_fortran(self):
        """
        Generates and parses a minimal Fortran `main` program.

        This method creates a simple Fortran program named `main` with:
    
        - An `implicit none` declaration to enforce explicit typing.
        - A basic print statement to indicate entry into the main program.
        - A `contains` section included to support the addition of internal
            subroutines if needed in future code generation.

        This stub is useful as a starting point for wrapping generated modules, 
        calling subroutines, or building up a driver program structure for testing 
        or benchmarking.

        Returns:
        --------
        parse_tree : fparser.two.Fortran2003.Program
            The parsed Abstract Syntax Tree (AST) of the generated main program.

        Raises:
        -------
        Exception
            If the Fortran source fails to parse.

        """
        code = """
        program main
        implicit none
        write(*,*)'--- inside the main program ---'
        contains
        end program main
        """
        try:
            reader = FortranStringReader(code, ignore_comments=False)
            parse_tree = self.parser(reader)
            logging.info("Successfully parsed main program code")
            return parse_tree
        except Exception as e:
            logging.error(f"Failed to parse main program code, Error: {e}")
            raise

    def write_fortran_code_to_file(self, code, file_path):
        """
        Writes formatted Fortran code to a specified file.

        This method takes a parsed Fortran code object, processes it to 
        ensure line length compliance or formatting via a line length processor,
        then writes the resulting string to the given file path.

        Parameters:
        -----------
        code : fparser.two.Fortran2003.Base
            The parsed Fortran code object to be converted and written.
        file_path : str
            The path of the file where the Fortran code will be saved.

        Raises:
        -------
        Exception
            If writing to the file or processing the code fails.

        """
        try:
            code = self.line_length.process(code.tostr())
            with open(file_path, 'w') as f:
                f.write(str(code))
            logging.info(f"Successfully wrote code to file: {file_path}")
        except Exception as e:
            logging.error(f"Failed to write code to file: {file_path}, Error: {e}")
            raise

    def update_global_module(self, input_dict, file_path, subroutine_name, module_tree):
        """
        Update the global Fortran module by injecting declarations, use statements,
        and I/O operations related to global variables and routines.

        This method performs the following steps:
        1. Locates the call statement to the specified subroutine within the module tree
            and replaces it with a code block that opens a binary file, writes data,
            and then closes the file.
        2. Inserts collected USE statements and variable declarations into the module's
            specification part.
        3. Inserts initialization and allocation statements into the appropriate subroutines
            (e.g., 'declaration_initialization' and 'initialization') within the module's
            subprogram part.
        4. Handles OpenACC declarations for device data management by adding relevant
            directives.
        5. Finally, writes the updated Fortran module code to the specified file path.

        Args:
            input_dict (dict): Dictionary of variables or declarations to add (not directly used here but related to overall context).
            file_path (str): Path where the updated Fortran module source code will be saved.
            subroutine_name (str): Name of the subroutine whose call site is to be updated.
            module_tree (F23.Tree): Parsed Fortran module tree representing the source code.

        Raises:
            AssertionError: If unexpected node types are encountered during tree traversal.
            Exception: Logs and re-raises any exceptions that occur during processing.

        Logging:
            Logs success or failure of the module update process.
        """
        try:
            self.out_module = self.out_module_fortran(subroutine_name)
            write_stmt_code = "\n".join(self.write_stmt)
            for call in walk(module_tree, F23.Call_Stmt):
                assert isinstance(call.children[0], F23.Name), f"Expected F23.Name, but got {type(call.children[0])}"
                assert isinstance(call.children[1], F23.Actual_Arg_Spec_List), \
                        f"Expected F23.Actual_Arg_Spec_List, but got {type(call.children[1])}"
                if call.children[0].tostr() == subroutine_name:
                    code_template = (
                            f"{call.tostr()}\n"
                            f"open(unit=1363, file='{self.benchmark_dir}/{subroutine_name}/global.bin', form='unformatted', status='replace')\n"
                            f"{write_stmt_code}\n"
                            "close(1363)"
                            )
                    call.parent.children[call.parent.children.index(call)] = self.parse_fortran_statement(code_template)
                    break

            for node in self.out_module.content:
                if isinstance(node, F23.Module):
                    for idx, subnode in enumerate(node.content):
                        if isinstance(subnode, F23.Specification_Part):
                            if self.add_to_usestm:
                                for stmt in self.add_to_usestm:
                                    subnode.content.insert(0, stmt)
                            ldx = len(subnode.content) - 1
                            for stmt in self.add_to_module:
                                subnode.content.insert(ldx + 1, stmt)
                                ldx += 1
                            if self.acc_declare_copyin:
                                subnode.content.insert(ldx + 1, self.acc_declare_copyin_cmd)
                                ldx += 1
                            if self.acc_declare_create:
                                subnode.content.insert(ldx + 1, self.acc_declare_create_cmd)
                                ldx += 1
                        elif isinstance(subnode, F23.Module_Subprogram_Part):
                            for jdx, subsubnode in enumerate(subnode.content):
                                if isinstance(subsubnode, F23.Subroutine_Subprogram):
                                    subroutine = walk(subsubnode, F23.Name)[0].string
                                    for kdx, subsubsubnode in enumerate(subsubnode.content):
                                        if isinstance(subsubsubnode, F23.Execution_Part):
                                            ldx = len(subsubsubnode.content) - 1
                                            if subroutine == 'declaration_initialization':
                                                for stmt in self.reads_in_decleration_routine:
                                                    subsubsubnode.content.insert(ldx + 1, stmt)
                                                    ldx += 1
                                                for stmt in self.add_to_routin:
                                                    subsubsubnode.content.insert(ldx + 1, stmt)
                                                    ldx += 1
                                                for stmt in self.reads_in_read_routine:
                                                    subsubsubnode.content.insert(ldx + 1, stmt)
                                                    ldx += 1
                                                subsubsubnode.content.insert(ldx + 1,F23.Close_Stmt(f"close(1363)"))
                                                ldx += 1
                                                if self.acc_declare_create:
                                                    subsubsubnode.content.insert(ldx + 1, self.acc_update_device_cmd)
                                                    ldx += 1
            logging.info("Successfully updated the global module")
            self.write_fortran_code_to_file(self.out_module, file_path)
        except Exception as e:
            logging.error(f"Failed to update global module, Error: {e}")
            raise

    def update_main_program(
            self,
            custom_dec_inout,
            custom_subroutine_trees,
            call_stmts,
            var_modif,
            file_path,
            subroutine_name,
            dummy_args,
            module_tree,
            childs_subroutine_tree=None,
            openacc=False,
            dummy_add_decl=None,
            error_flag=None,
            acc_data_copyin=None
            ):
        """
        Updates the Fortran main program by modifying its structure, adding subroutine calls, 
        variable declarations, initialization routines, error handling, and OpenACC directives 
        for parallelism. The method processes the given subroutine information and writes the 
        modified program to the specified file path.

        Parameters:
            custom_dec_inout (list): A list of custom variable declarations and input/output 
                                  specifications to be inserted into the Fortran program’s 
                                  specification part.
            custom_subroutine_trees (list): A list of subroutine trees to be inserted into the 
                                        main program.
            call_stmts (list): A list of Fortran `Call_Stmt` objects representing subroutine 
                           calls to be inserted into the program.
            var_modif (set): A set of variable names that have been modified within the 
                         subroutine. Used for tracking variable changes.
            file_path (str): The file path where the modified Fortran code will be written to.
            subroutine_name (str): The name of the subroutine to be modified in the main program.
            dummy_args (list): A list of dummy argument names that are passed to subroutines.
            module_tree (F23.Module_Stmt): The module tree of the program, which includes 
                                       declarations and subroutines that need to be modified.
            childs_subroutine_tree (optional, list): A list of child subroutine trees to be 
                                                  inserted into the program. Default is `None`.
            openacc (bool, optional): If `True`, OpenACC directives for parallelism and data 
                                  management are inserted into the program. Default is `False`.
            dummy_add_decl (F23.Declaration_Stmt, optional): A Fortran declaration statement 
                                                          for dummy arguments to be added. 
                                                          Default is `None`.
            error_flag (dict, optional): A dictionary containing error flags for variables. 
                                     Used to insert error-handling code. Default is `None`.

        Operation:
            - Initializes and parses the main program and module information.
            - Handles dummy arguments and builds initialization routines for them.
            - Updates variable declarations and adds error-handling code based on the `error_flag`.
            - Inserts initialization code, such as `read` routines, for dummy arguments.
            - Modifies the `Specification_Part` of the program by inserting new variable 
                declarations and subroutine calls.
            - Adds performance benchmarking code using `SYSTEM_CLOCK` and writes the result 
                to an output file.
            - If `openacc` is enabled, inserts OpenACC directives for parallel loops and data 
                management, such as `COPYIN`, `UPDATE SELF`, and `PARALLEL LOOP`.
            - Includes subroutine calls for initialization, execution time measurements, and 
                variable modifications.
            - Handles child subroutine trees and inserts them at the appropriate locations.
            - Writes the modified Fortran code to the specified file path.

        Returns:
            None: The method does not return a value, but modifies the Fortran program in place 
              and writes it to the provided file path.
        """
        try:
            self.out_main = self.out_main_fortran()
            custom_module_name = walk(walk(self.out_module,F23.Module_Stmt), F23.Name)[0].string
            custom_subroutines_names = [name.string for name in walk(walk(self.out_module,F23.Subroutine_Stmt),F23.Name)]
            #specification_part = self.remove_intent_and_save(custom_dec_inout)
            initialization_part = self.initialization_statement(custom_dec_inout)
            if self.dummy_list:
                print('need to build an initialization for in/inout dummy args: ')
                specification_part_dummy = self.remove_intent_and_save(self.dummy_list)
                block_tree = self.generate_read_routine(specification_part_dummy, initialization_part, subroutine_name)

            if dummy_add_decl is not None:
                custom_dec_inout.append(dummy_add_decl)
            if error_flag is not None:
                if error_flag.keys():
                    for key in error_flag.keys():
                        custom_dec_inout.append(error_flag[key]['error_flag_decl'])
            specification_part = self.remove_intent_and_save(custom_dec_inout)

            if initialization_part:
                self.write_stmt = []
                for call in walk(module_tree, F23.Call_Stmt):
                    assert isinstance(call.children[0], F23.Name), f"Expected F23.Name, but got {type(call.children[0])}"
                    assert isinstance(call.children[1], F23.Actual_Arg_Spec_List), \
                            f"Expected F23.Actual_Arg_Spec_List, but got {type(call.children[1])}"
                    if call.children[0].tostr() == subroutine_name:
                        arg_string = [string.strip() for string in call.children[1].tostr().split(',')]
                        for rstmt in initialization_part:
                            assert isinstance(rstmt.children[0].children[2], F23.Input_Item_List)
                            assert len(rstmt.children[0].children[2].children) == 1
                            arg = rstmt.children[0].children[2].tostr()
                            corresponding_element = arg_string[dummy_args.index(arg)]
                            self.write_stmt.append(F23.Write_Stmt(f"write(1363){corresponding_element}").tostr())
                        write_dummy_code = "\n".join(self.write_stmt)
                        code_template = (
                                f"{call.tostr()}\n"
                                f"open(unit=1363, file='{self.benchmark_dir}/{subroutine_name}/dummy.bin', form='unformatted', status='replace')\n"
                                f"{write_dummy_code}\n"
                                "close(1363)"
                                )
                        call.parent.children[call.parent.children.index(call)] = self.parse_fortran_statement(code_template)
                        break

            for node in self.out_main.content:
                if isinstance(node, F23.Main_Program):
                    for idx, subnode in enumerate(node.content):
                        if isinstance(subnode, F23.Specification_Part):
                            use = walk(subnode, F23.Use_Stmt)
                            kdx = len(use) - 1
                            use_stmt = 'use ' + custom_module_name
                            subnode.content.insert(kdx + 1, F23.Use_Stmt(use_stmt))
                            kdx = len(subnode.content) - 1
                            for stmt in specification_part:
                                is_modified = any(name.string in var_modif for name in walk(stmt, F23.Entity_Decl))
                                if is_modified:
                                    if openacc:
                                        subnode.content.insert(kdx + 1, self.add_entity_to_declaration(stmt, var_modif))
                                    else:
                                        subnode.content.insert(kdx + 1, stmt)
                                else:
                                    subnode.content.insert(kdx + 1, stmt)
                                kdx += 1
                        elif isinstance(subnode, F23.Execution_Part):
                            kdx = len(subnode.content) - 1
                            #for name in custom_subroutines_names:
                            subroutine_call = "Call declaration_initialization"
                            subnode.content.insert(kdx + 1, F23.Call_Stmt(subroutine_call))
                            kdx += 1

                            subnode.content.insert(kdx + 1, self.create_call_stmt(block_tree))
                            kdx += 1

                            code_start = """
                            call SYSTEM_CLOCK(ic0, icr, ic)
                            start_time = ic0*1.0/icr
                            """

                            subnode.content.insert(kdx + 1, self.parse_fortran_statement(code_start))
                            kdx += 1

                            subnode.content.insert(kdx + 1, call_stmts[0])
                            kdx += 1

                            code_end = f"""
                            call SYSTEM_CLOCK(ic0, icr, ic)
                            stop_time = ic0*1.0/icr
                            WRITE(*,*) "Execution time : ",stop_time - start_time
                            open(unit=1363, file='{self.benchmark_dir}/{subroutine_name}/time.txt', status='unknown', position='append')
                            WRITE(1363,*) stop_time - start_time
                            close(1363)
                            """

                            subnode.content.insert(kdx + 1, self.parse_fortran_statement(code_end))
                            kdx += 1

                            write_statements = []
                            for modified_var in var_modif:
                                stmt = F23.Write_Stmt(f"write(1363) {modified_var}") 
                                write_statements.append(stmt.tostr()) 
                            write_stmt_code = "\n".join(write_statements)
                            code_template = (
                                f"open(unit=1363, file='{self.benchmark_dir}/{subroutine_name}/output.bin', form='unformatted', status='replace')\n"
                                f"{write_stmt_code}\n"
                                "close(1363)"
                            )
                            
                            subnode.content.insert(kdx + 1, self.parse_fortran_statement(code_template))
                            kdx += 1

                            if openacc:
                                for modified_var in var_modif:
                                    stmt_str = modified_var + '_copy' + '=' + modified_var
                                    subnode.content.insert(kdx + 1, F23.Assignment_Stmt(stmt_str))
                                    kdx += 1

                                subroutine_call = "Call declaration_initialization"
                                subnode.content.insert(kdx + 1, F23.Call_Stmt(subroutine_call))
                                kdx += 1
                                subnode.content.insert(kdx + 1, self.create_call_stmt(block_tree))
                                kdx += 1

                                reductions = ''
                                if error_flag.keys():
                                    all_arrors = ', '.join([err for err in list(error_flag.keys())])
                                    reductions =f'REDUCTION(+:{all_arrors})'
                                    for key in error_flag.keys():
                                        subnode.content.insert(kdx + 1, error_flag[key]['error_flag_init'])
                                        kdx += 1
                            
                                if acc_data_copyin:
                                    copyinlist = ', '.join([item for item in acc_data_copyin])
                                    acc_copyin_cmd = Processor().parse_fortran_comment(f"!$ACC ENTER DATA COPYIN({copyinlist})")
                                    acc_delete_cmd = Processor().parse_fortran_comment(f"!$ACC EXIT DATA DELETE({copyinlist})")
                                    subnode.content.insert(kdx + 1, acc_copyin_cmd)
                                    kdx += 1

                                acc_kernels_cmd, acc_end_kernels_cmd = Processor().parse_fortran_comment(f"!$ACC PARALLEL LOOP INDEPENDENT {reductions}"),\
                                    Processor().parse_fortran_comment(f"!$ACC END PARALLEL")

                                subnode.content.insert(kdx + 1, self.parse_fortran_statement(code_start))
                                kdx += 1

                                subnode.content.insert(kdx + 1, acc_kernels_cmd)
                                kdx += 1
                                subnode.content.insert(kdx + 1, call_stmts[1])
                                kdx += 1
                                subnode.content.insert(kdx + 1, acc_end_kernels_cmd)
                                kdx += 1

                                subnode.content.insert(kdx + 1, self.parse_fortran_statement(code_end))
                                kdx += 1

                                acc_update_self_str = ', '.join([modified_var for modified_var in var_modif])# \
                                    #if modified_var in self.acc_declare_create])
                                acc_update_self_cmd = self.parse_fortran_comment(f"!$ACC UPDATE SELF({acc_update_self_str})")
                                subnode.content.insert(kdx + 1, acc_update_self_cmd)
                                kdx += 1
                                if acc_data_copyin:
                                    subnode.content.insert(kdx + 1, acc_delete_cmd)
                                    kdx += 1

                                for modified_var in var_modif:
                                    var_info = var_modif[modified_var]
                                    if_construct = self.check_point(modified_var, modified_var+'_copy', var_info)
                                    subnode.content.insert(kdx + 1, if_construct)
                                    kdx += 1

                                if error_flag.keys():
                                    for key in error_flag.keys():
                                        subnode.content.insert(kdx + 1, error_flag[key]['write_calls'])
                                        kdx += 1
                            
                        elif isinstance(subnode, F23.Internal_Subprogram_Part):
                            if self.dummy_list:
                                node.content.insert(idx + 1, block_tree)
                            for custom_subroutine_tree in custom_subroutine_trees:
                                node.content.insert(idx + 1, custom_subroutine_tree)
                            if childs_subroutine_tree is not None:
                                for child_subroutine in childs_subroutine_tree:
                                    node.content.insert(idx + 1, child_subroutine)
            logging.info("Successfully updated the main program")
            self.write_fortran_code_to_file(self.out_main, file_path)
        except Exception as e:
            logging.error(f"Failed to update main program, Error: {e}")
            raise

    def create_call_stmt(self, subroutine_tree):
        """
        Constructs a Fortran CALL statement from the AST of a parsed subroutine.

        This method extracts the subroutine name from a provided `Subroutine_Stmt` 
        node within the subroutine's AST and returns a corresponding 
        `Call_Stmt` object (parsed using fparser).

        Parameters:
        -----------
        subroutine_tree : fparser.two.Fortran2003.Block
            The AST node representing the full subroutine block (e.g., returned from `parse_fortran_string` or similar).

        Returns:
        --------
        subroutine_call_obj : fparser.two.Fortran2003.Call_Stmt
            A parsed `CALL` statement targeting the subroutine, which can be inserted
            into other Fortran program structures.

        Raises:
        -------
        Exception
            If the subroutine name cannot be extracted or the CALL statement cannot be constructed.

        """
        try:
            subroutine_stmt = walk(subroutine_tree, F23.Subroutine_Stmt)[0]
            subroutine_stmt_string = subroutine_stmt.tostr()
            subroutine_name = subroutine_stmt_string.replace('SUBROUTINE', '').strip()
            subroutine_call = f"CALL {subroutine_name}"
            subroutine_call_obj = F23.Call_Stmt(subroutine_call)
            return subroutine_call_obj
        except Exception as e:
            print(f"An error occurred in creating a Call_Stmt object: {e}")
            raise

    def generate_read_routine(self, specification_part, initialization_part, subroutine_name):
        """
        Generates a complete Fortran subroutine that reads input data from file
        and initializes dummy variables.

        This method creates a new subroutine based on a template, inserts dummy
        argument declarations and initialization `READ` statements, and finalizes
        the subroutine with a `CLOSE` statement for the file unit.

        Parameters:
            specification_part (list):
                A list of `F23.Type_Declaration_Stmt` nodes that declare dummy variables
                and their types, shapes, etc.

            initialization_part (list):
                A list of `F23.Read_Stmt` nodes used to read input values from a binary file
                into the declared dummy arguments.

            subroutine_name (str):
                Name of the generated subroutine, used to customize the header.

        Returns:
            Fparser2Node:
                An updated Fortran subroutine block (`Fparser2Node`) with appropriate declarations,
                dummy argument interface, and input reading logic inserted.

        Raises:
            Exception:
                If any error occurs during construction of the subroutine block, it is logged and raised.
        """
        try:
            block = self.initiate_empty_routine(subroutine_name)
            if hasattr(block, "content"):
                idc = 0
                while idc < len(block.content):
                    child = block.content[idc]
                    if isinstance(child, F23.Subroutine_Stmt):
                        subroutine_stmt = "subroutine "
                        for grandchild in child.children:
                            if isinstance(grandchild, F23.Name):
                                subroutine_stmt += f"{grandchild.tostr()}"
                        dummy_arg_list = []
                        for stmt in specification_part:
                            entity_dec = walk(stmt, F23.Entity_Decl)
                            for entity in entity_dec:
                                dummy_arg_list.append(entity.tostr())
                        dummy_arg = ', '.join([name for name in dummy_arg_list])
                        subroutine_stmt += f"({dummy_arg})"
                        block.content[idc] = F23.Subroutine_Stmt(subroutine_stmt)
                        for stmt in specification_part:
                            block.content.insert(idc + 1, stmt)
                    elif isinstance(child, F23.Execution_Part):
                        kdx = len(child.content) - 1
                        for stmt in initialization_part:
                            child.content.insert(kdx + 1, stmt)
                            kdx += 1
                        child.content.insert(kdx + 1,F23.Close_Stmt(f"close(1363)"))
                        kdx += 1
                    idc += 1
                return block
        except Exception as e:
            logging.error(f"Failed to generate read routine, Error: {e}")
            raise

    def initialization_statement(self, items):
        """
        Separates Fortran declarations and generates appropriate initialization
        `read(...)` or `write(...)` statements for variables.

        Used when variables are declared without initialization or
        when `ALLOCATABLE` is not present.

        Parameters:
            items (list): List of declaration nodes (F23.Type_Declaration_Stmt).

        Returns:
            read_list (list): List of Fortran read statements for each variable.

        Populates:
            - self.write_stmt → Stores `write(...)` strings.
            - self.dummy_list → Stores modified declaration statements.
        """
        read_list = []
        items_sep = []
        self.dummy_list = []
        for item in items:
            if len(walk(item, F23.Entity_Decl)) > 1:
                node_list = self.separate_entity_declarations(item)
                for node in node_list:
                    items_sep.append(node)
            else:
                items_sep.append(item)
        try:
            for item in items_sep:
                init = True
                intent = walk(item, F23.Intent_Spec)
                if F23.Intent_Spec('OUT') in intent:
                    init = False
                for child in item.children:
                    if isinstance(child, F23.Intrinsic_Type_Spec):
                        var_type = child.tostr()
                    if isinstance(child, F23.Entity_Decl_List):
                        var_name = child.tostr()
                if init:
                    self.dummy_list.append(item)
                    code_template = f"""
                    read(1363, iostat = ier){var_name}
                    if (ier /= 0) then
                    write(*,*) 'Error reading from file for {var_name}. ',' IOSTAT : ', ier
                    endif
                    """
                    read_list.append(self.parse_fortran_statement(code_template))
                    self.write_stmt.append(F23.Write_Stmt(f"write(1363){var_name}").tostr())
            logging.info(f"processing initialization completed!")
            return read_list
        except Exception as e:
            logging.error(f"Error processing initialization: {e}")
            raise

    def add_declarations(self, input_dict, var_modif, openacc=False):
        """
        Processes and categorizes Fortran variable declarations and allocations
        into separate groups for further use, such as:

        - Adding to the module or routine headers.
        - Preparing OpenACC directives (e.g., `!$ACC DECLARE CREATE(...)`).
        - Tracking variables that need to be initialized via read statements.
    
        Parameters:
            input_dict (dict): Dictionary of declarations (var name → [declaration nodes]).
            var_modif (set): Set of variable names that are modified inside the subroutine.
    
        Populates:
            - self.add_to_module → declarations to be added to module.
            - self.add_to_routin → allocation statements to be added in routine body.
            - self.add_to_usestm → collected USE statements.
            - self.acc_declare_create / copyin → for OpenACC memory management.
            - self.reads_in_decleration_routine / reads_in_read_routine → categorized init methods.
            - self.write_stmt → write statements to be emitted to file.
            - self.acc_declare_create_cmd / copyin_cmd → formatted OpenACC directives.
        """
        try:
            self.add_to_module = []
            self.add_to_routin = []
            self.add_to_usestm = []
            self.acc_declare_create = []
            self.acc_declare_copyin = []
            self.reads_in_decleration_routine = []
            self.reads_in_read_routine = []
            self.write_stmt = []
            for key in sorted(input_dict):
                var_in_modif = False
                if key in var_modif:
                    var_in_modif = True
                for item in input_dict[key]:
                    is_dec_stmt = isinstance(item, F23.Type_Declaration_Stmt)
                    is_alo_stmt = isinstance(item, F23.Allocate_Stmt)
                    is_use_stmt = isinstance(item, F23.Use_Stmt)
                    if is_dec_stmt:
                        if var_in_modif:
                            if openacc:
                                self.add_to_module.append(self.add_entity_to_declaration(item, var_modif))
                            else:
                                self.add_to_module.append(item)
                        else:
                            self.add_to_module.append(item)
                        all_entity_names = walk(item, F23.Entity_Decl)
                        initialized = walk(item, F23.Initialization)
                        attr_spec = walk(item, F23.Attr_Spec)
                        if not initialized:
                            for entity_name in all_entity_names:
                                if openacc:
                                    self.acc_declare_create.append(entity_name.tostr())
                            if F23.Attr_Spec('ALLOCATABLE') not in attr_spec:
                                self.reads_in_decleration_routine.append(item)
                            else:
                                self.reads_in_read_routine.append(self.combine_allocate_declaration(input_dict[key]))
                        else:
                            if openacc:
                                for entity_name in all_entity_names:
                                    for child in entity_name.children:
                                        if isinstance(child, F23.Name):
                                            self.acc_declare_copyin.append(child.tostr())
                    if is_alo_stmt:
                        for allocation_stmt in self.add_entity_to_allocation(item, var_modif, openacc):
                            self.add_to_routin.append(allocation_stmt.children[0])
                    if is_use_stmt:
                        self.add_to_usestm.append(item)
            self.add_to_module = self.remove_intent_and_save(self.add_to_module)
            self.reads_in_decleration_routine = self.remove_intent_and_save(self.reads_in_decleration_routine)
            self.reads_in_decleration_routine = self.initialization_statement(self.reads_in_decleration_routine)
            self.reads_in_read_routine = self.initialization_statement(self.reads_in_read_routine)
            self.add_to_module = self.process_queue(self.add_to_module)
            if self.acc_declare_copyin:
                acc_declare_copyin_str = ', '.join([name for name in self.acc_declare_copyin])
                self.acc_declare_copyin_cmd = self.parse_fortran_comment(f"!$ACC DECLARE COPYIN({acc_declare_copyin_str})")
            if self.acc_declare_create:
                acc_declare_create_str = ', '.join([name for name in self.acc_declare_create])
                self.acc_declare_create_cmd = self.parse_fortran_comment(f"!$ACC DECLARE CREATE({acc_declare_create_str})")
                self.acc_update_device_cmd = self.parse_fortran_comment(f"!$ACC UPDATE DEVICE({acc_declare_create_str})")
            logging.info("Declarations and allocations processed successfully ")
        except Exception as e:
            logging.error(f"Failed to process declarations and allocations, Error: {e}")
            raise

    def process_queue(self, input_list):
        """
        Organizes a list of Fortran declaration statements into a logical and structured order.

        This method is designed to sort variable declarations based on their characteristics,
        which is particularly important for ensuring correct code generation and proper
        compilation behavior in Fortran.

        The reordering follows these rules:
            - PARAMETER constants (non-arrays) come first.
            - Regular scalar variables follow.
            - Arrays and ALLOCATABLE declarations are placed at the end.

        Specifically:
            - If a declaration includes the PARAMETER attribute and is not an array:
                - If it has initialization, it's added to the end of the PARAMETER section.
                - If it lacks initialization, it's inserted at the very beginning.
            - ALLOCATABLE declarations and variables with explicit shape (arrays) go last.
            - All others (typically scalar declarations) are kept in the middle.

        Parameters:
            input_list (list): A list of F23.Type_Declaration_Stmt nodes representing 
                           variable declarations to be sorted.

        Returns:
            list: A reordered list of declaration statements following the above rules.

        Raises:
            Exception: If any error occurs during processing.
    
        Logging:
            Logs information about the sorting process and any errors encountered.
        """
        try:
            queue = deque(input_list)
            left_list = []
            middle_list = []
            right_list = []
            while queue:
                element = queue.popleft()
                attr_spec = [case.string for case in walk(element, F23.Attr_Spec)]
                array = walk(element, F23.Explicit_Shape_Spec)
                if 'PARAMETER' in attr_spec and not array:
                    initialization = walk(walk(element, F23.Initialization), F23.Name)
                    if initialization:
                        left_list.append(element)
                    else:
                        left_list.insert(0, element)
                elif 'ALLOCATABLE' in attr_spec or array:
                    right_list.append(element)
                else:
                    middle_list.append(element)
            combined_list = left_list + middle_list + right_list
            logging.info(f"Processing complete. PARAMETER elements sent to the left.")
            return list(combined_list)
        except Exception as e:
            logging.error(f"An error occurred while processing the queue: {e}")
            raise

    def compile_and_run(self, base_dir, modules_dir, mode="CPU"):
        """
        Compiles and runs all generated subroutines in their respective directories.

        This method searches through subdirectories inside the given `modules_dir` path, 
        sets up the environment variables needed for compilation, and invokes `make` 
        using the provided Makefile. If the required binary input files (`dummy.bin` 
        and `global.bin`) exist in the benchmark directory, it proceeds to execute 
        the compiled subroutine binary.

        Parameters:
            base_dir (str): 
                The root directory containing the Makefile and benchmark structure.

            modules_dir (str): 
                The directory (relative to `base_dir`) where each subroutine's 
                compiled files and sources reside.

            mode (str, optional): 
                Compilation mode, typically "CPU" or "GPU". Defaults to "CPU".

        Returns:
            int:
                - Returns 0 if all subroutines were successfully compiled and executed.
                - Returns 1 if any compilation or execution step failed.

        Side Effects:
            - Changes the current working directory (`os.chdir`).
            - Sets environment variables `SUBDIR_PATH` and `MODE`.
            - Executes shell commands via `os.system`.
            - Prints colored status messages to the terminal.
        """
        target_module_dir_path = os.path.join(base_dir, modules_dir)
        for subdir in os.listdir(target_module_dir_path):
            subdir_path = os.path.join(target_module_dir_path, subdir)
            if os.path.isdir(subdir_path):
                print('\033[32m' + f"Compiling and running in {subdir_path}..." + '\033[0m')
                os.environ["SUBDIR_PATH"] = subdir_path
                os.environ["MODE"] = mode
                os.chdir(subdir_path)
                os.system("make clean -f {}".format(os.path.join(base_dir, "Makefile")))
                os.system("make -f {}".format(os.path.join(base_dir, "Makefile")))
                if os.path.exists(subdir):
                    print('\033[32m' + "Compilation process completed!" + '\033[0m')
                    dummy_bin = os.path.join(self.benchmark_dir, subdir, "dummy.bin")
                    global_bin = os.path.join(self.benchmark_dir, subdir, "global.bin")
                    if os.path.exists(dummy_bin) and os.path.exists(global_bin):
                        print('\033[32m' + "Benchmark files exist. Now running the unit tests ..." + '\033[0m')
                        os.system("./{}".format(subdir))
                        print('\033[32m' + f"Execution completed in {subdir_path}" + '\033[0m')
                    else:
                         if not os.path.exists(dummy_bin):
                             print('\033[31m' + f"Missing file: {dummy_bin}" + '\033[0m')
                         if not os.path.exists(global_bin):
                             print('\033[31m' + f"Missing file: {global_bin}" + '\033[0m')
                         print('\033[31m' + f"Benchmark files do not exist yet. Run the modified main code and then python executive.py " + '\033[0m')
                else:
                    print('\033[31m' + "Compilation failed or main_program not generated." + '\033[0m')
                    return 1
        os.chdir(base_dir)
        return 0
