Python_templates:
    Python_global_normal_template:
        name: "Python_global_normal_template"
        template: |
            import numpy as np
            import logging
            from scipy.io import FortranFile
            import time
            import functools

            nice = np.int32(8)
            ncirc = np.int32(3)
            nsnow = np.int32(3)
            nslm = np.int32(11)
            nvm = np.int32(15)
            nstm = np.int32(3)
            kjpindex = np.int32(4717)

            ier = np.int32(0)
            ic0 = np.int32(0)
            ic = np.int32(0)
            icr = np.float64(0.0)
            start_time = np.float64(0.0)
            stop_time = np.float64(0.0)

            def declaration_initialization():
                print("--- add the declaration and initialization in module global ---")

    Python_global_class_template:
        name: "Python_global_class_template"
        template: |
            import numpy as np
            import logging
            from scipy.io import FortranFile
            import time
            import functools

            class Global_module:
                def __init__(self):

                    self.nice = np.int32(8)
                    self.ncirc = np.int32(3)
                    self.nsnow = np.int32(3)
                    self.nslm = np.int32(11)
                    self.nvm = np.int32(15)
                    self.nstm = np.int32(3)
                    self.kjpindex = np.int32(4717)

                    self.ier = np.int32(0)
                    self.ic0 = np.int32(0)
                    self.ic = np.int32(0)
                    self.icr = np.float64(0.0)
                    self.start_time = np.float64(0.0)
                    self.stop_time = np.float64(0.0)

                def declaration_initialization(self):
                    pass

    Python_main_template:
        name: "Python_main_template"
        template: |
            import os
            import numpy as np
            import logging
            from scipy.io import FortranFile

            def main():
                print('--- inside the main program ---')

            if __name__ == "__main__":
                main()

    Python_read_for_loop_class_template:
        name: "Python_read_for_loop_class_template"
        template: |
            print(f'--- add the declaration and initialization in module global ---')
            path = f'{benchmark_dir}/{subroutine_name}/global.bin'
            ffile = FortranFile(path, 'r')
            for attr_name in []:
                attribute = getattr(self,attr_name)
                if isinstance(attribute, np.ndarray):
                    arr_shape = attribute.shape
                    if np.issubdtype(attribute.dtype, np.float64):
                        data = ffile.read_reals(np.float64)
                    elif np.issubdtype(attribute.dtype, np.int32) or np.issubdtype(attribute.dtype, np.bool):
                        data = ffile.read_ints(np.int32)

                    if data.size != np.prod(arr_shape):
                        continue
                    value = data.reshape(arr_shape, order='F')
                    setattr(self, attr_name, value)

    Python_read_dummy_template:
        name: "Python_read_dummy_template"
        template: |
            def read_dummy():
                print(f'--- inside the read dummy routine for {subroutine_name} ---')
                path = f'{benchmark_dir}/{subroutine_name}/dummy.bin'
                ffile = FortranFile(path, 'r')
                for var in []:
                    if isinstance(var, np.ndarray):
                        arr_shape = var.shape
                        if np.issubdtype(var.dtype, np.float64):
                            data = ffile.read_reals(np.float64)

                        elif np.issubdtype(var.dtype, np.int32) or np.issubdtype(var.dtype, np.bool):
                            data = ffile.read_ints(np.int32)

                        if data.size != np.prod(arr_shape):
                            continue
                        var[:] = data.reshape(arr_shape, order='F')

    Python_timer_template:
        name: "Python_timer_template"
        template: |
            def timer(func):
                @functools.wraps(func)
                def wrapper(*args, **kwargs):
                    start_time = time.perf_counter()
                    result = func(*args, **kwargs)
                    end_time = time.perf_counter()
                    duration = end_time - start_time
                    print(f"[TIMER] '{func.__name__}' executed in {duration:.6f} seconds")
                    path = $path
                    with open(path,"a") as f:
                        f.write(f"[TIMER] Python: '{func.__name__}' executed in {duration:.6f} seconds \n")
                    return result
                return wrapper

    Python_test_output_template:
        name: "Python_test_output_template"
        template: |
            fortran_value = None
            if isinstance(value,np.ndarray):
                arr_shape = value.shape
                if np.issubdtype(value.dtype, np.float64):
                    fortran_value = ffile.read_reals(np.float64).reshape(arr_shape, order='F')
                elif np.issubdtype(value.dtype, np.int32) or np.issubdtype(value.dtype, np.bool):
                    fortran_value = ffile.read_ints(np.int32).reshape(arr_shape, order='F')

                if np.allclose(value,fortran_value):
                    print(f'Test passed: Variable:{variable} is equal to FORTRAN variable: {variable}')
                else:
                    print(f'Test failed: All elements in {variable} do not match to FORTRAN variable: {variable}')
                    print(f' Maximum absolute error: {np.max(abs(value - fortran_value))}')
                    print(f' Min and max of python value: {value.min()}, {value.max()}')
                    print(f' Min and max of FORTRAN value: {fortran_value.min()}, {fortran_value.max()}')

            elif np.isscalar(value):
                if np.issubdtype(value.dtype, np.int32) or np.issubdtype(value.dtype, np.bool):
                    fortran_value = ffile.read_ints(np.int32)[0]
                elif np.issubdtype(value.dtype, np.float64):
                    fortran_value = ffile.read_reals(np.float64)[0]

                if np.isclose(value,fortran_value):
                    print(f' Test passed: Variable:{variable} is equal to FORTRAN variable: {variable}')
                else:
                    print(f'Test failed: Python variable:{variable} do not match to FORTRAN variable: {variable}')

JAX_templates:

    JAX_timer_template:
        name: "JAX_timer_template"
        template: |
            def timer(func, *args):
                start = time.perf_counter()
                out = func(*args)
                jax.tree_util.tree_map(
                    lambda x: x.block_until_ready() if hasattr(x, "block_until_ready") else x,
                    out,
                )
                end = time.perf_counter()
                name = getattr(func, "__name__", func.func.__name__)
                duration = end - start
                print(f"[TIMER JAX] '{name}' executed in {duration:.6f}s")
                path = $path
                with open(path, 'a') as f:
                    f.write(
                        f"[TIMER JAX] Python: '{name}' executed in {duration:.6f} seconds\n"
                    )
                    print(f"Saved the benchmark in:{path}")
                return out
