!
!  io_generic.f90
!  A generic Fortran I/O template.
!
!  Every OPEN statement uses only the specifiers whose defaults differ from
!  the desired behaviour:
!
!     newunit=  (no default)          always
!     file=     (default fort.n)      always
!     status=   (default 'unknown')   whenever we mean replace / old / new
!     form=     (default 'formatted') only for unformatted
!     access=   (default 'sequential') only for direct or stream
!     position= (default 'asis')      only for append
!     recl=     (no default)          only for direct access
!     iostat=   (no default)          only when we want to handle errors
!
!  Everything else is left at the compiler default.
!

program io_generic
  implicit none

  integer, parameter :: n = 5
  real    :: arr(n)
  real    :: back(n)
  real    :: mat(n,3)
  integer :: i

  ! Fill the array and a small matrix
  do i = 1, n
    arr(i)   = real(i) * 1.5
    mat(i,1) = real(i)
    mat(i,2) = real(i) ** 2
    mat(i,3) = 1.0 / real(i)
  end do

  !
  ! 1) print / write to stdout -- three flavours
  !
  call demo_stdout(arr, n)

  !
  ! 2) Text, list-directed, minimal OPEN
  !
  call dump_formatted(arr, n, "/home/kardaneh/Fgpt/benchmark/demo-ios/out_list.txt")
  call load_formatted(back, n, "/home/kardaneh/Fgpt/benchmark/demo-ios/out_list.txt")
  call check_equal(arr, back, n, "dump/load list-directed")

  !
  ! 3) Text, explicit format, minimal OPEN
  !
  call dump_formatted_fmt(arr, n, "/home/kardaneh/Fgpt/benchmark/demo-ios/out_fmt.txt")
  call load_formatted(back, n, "/home/kardaneh/Fgpt/benchmark/demo-ios/out_fmt.txt")
  call check_equal(arr, back, n, "dump/load formatted")

  !
  ! 4) Binary, minimal OPEN
  !
  call dump_unformatted(arr, n, "/home/kardaneh/Fgpt/benchmark/demo-ios/out_bin.dat")
  call load_unformatted(back, n, "/home/kardaneh/Fgpt/benchmark/demo-ios/out_bin.dat")
  call check_equal(arr, back, n, "dump/load unformatted")

  !
  ! 5) Append to a text file
  !
  call append_formatted(arr, n, "/home/kardaneh/Fgpt/benchmark/demo-ios/out_list.txt")

  !
  ! 6) Text file with a header
  !
  call dump_with_header(arr, n, "/home/kardaneh/Fgpt/benchmark/demo-ios/out_hdr.txt", &
                        "generated by io_generic.f90")

  !
  ! 7) Multi-column text
  !
  call dump_multicol(mat, n, 3, "/home/kardaneh/Fgpt/benchmark/demo-ios/out_mat.txt")
  call load_multicol(mat, n, 3, "/home/kardaneh/Fgpt/benchmark/demo-ios/out_mat.txt")

  !
  ! 8) File queries
  !
  print '(A,L1)',  " out_list.txt   exists? ", inq_file_exists("/home/kardaneh/Fgpt/benchmark/demo-ios/out_list.txt")
  print '(A,L1)',  " missing.txt    exists? ", inq_file_exists("/home/kardaneh/Fgpt/benchmark/demo-ios/missing.txt")
  print '(A,I0)',  " out_list.txt   bytes:  ", inq_file_size("/home/kardaneh/Fgpt/benchmark/demo-ios/out_list.txt")

  print *, "Program completed successfully!"

contains

  !
  ! DEMO : stdout
  !
  subroutine demo_stdout(arr, size)
    implicit none
    integer, intent(in) :: size
    real,    intent(in) :: arr(size)
    integer :: i

    print *, "--- print * (list-directed) ---"
    do i = 1, size
      print *, "Element ", i, " = ", arr(i)
    end do

    print *, "--- write(*,*) (list-directed) ---"
    write(*, *) "Array contents:"
    do i = 1, size
      write(*, *) " Element ", i, " : ", arr(i)
    end do

    print *, "--- write(*,'(...)') (explicit format) ---"
    do i = 1, size
      write(*, '(A,I4,A,F12.6)') " Element ", i, " : ", arr(i)
    end do
  end subroutine demo_stdout

  ! --
  ! dump_formatted  -- text, list-directed
  ! --
  subroutine dump_formatted(arr, size, filename)
    implicit none
    integer, intent(in)  :: size
    real,    intent(in)  :: arr(size)
    character(len=*), intent(in) :: filename
    integer :: unit, i

    open(newunit=unit, file=filename, status='replace')
    do i = 1, size
      write(unit, *) arr(i)
    end do
    close(unit)
  end subroutine dump_formatted

  ! --
  ! load_formatted  -- read one value per line, list-directed
  ! --
  subroutine load_formatted(arr, size, filename)
    implicit none
    integer, intent(in)  :: size
    real,    intent(out) :: arr(size)
    character(len=*), intent(in) :: filename
    integer :: unit, i, ios

    open(newunit=unit, file=filename, status='old', iostat=ios)
    if (ios /= 0) stop "load_formatted: cannot open file"
    do i = 1, size
      read(unit, *, iostat=ios) arr(i)
      if (ios /= 0) stop "load_formatted: read error"
    end do
    close(unit)
  end subroutine load_formatted

  ! --
  ! dump_formatted_fmt  -- text, explicit format
  ! --
  subroutine dump_formatted_fmt(arr, size, filename)
    implicit none
    integer, intent(in)  :: size
    real,    intent(in)  :: arr(size)
    character(len=*), intent(in) :: filename
    integer :: unit, i

    open(newunit=unit, file=filename, status='replace')
    do i = 1, size
      write(unit, '(ES24.16)') arr(i)
    end do
    close(unit)
  end subroutine dump_formatted_fmt

  ! --
  ! dump_unformatted  -- binary, one record with the array
  ! --
  subroutine dump_unformatted(arr, size, filename)
    implicit none
    integer, intent(in)  :: size
    real,    intent(in)  :: arr(size)
    character(len=*), intent(in) :: filename
    integer :: unit

    open(newunit=unit, file=filename, status='replace', form='unformatted')
    write(unit) size
    write(unit) arr
    close(unit)
  end subroutine dump_unformatted

  ! --
  ! load_unformatted  -- binary, matching dump_unformatted
  ! --
  subroutine load_unformatted(arr, size, filename)
    implicit none
    integer, intent(in)  :: size
    real,    intent(out) :: arr(size)
    character(len=*), intent(in) :: filename
    integer :: unit, nread, ios

    open(newunit=unit, file=filename, status='old', &
         form='unformatted', iostat=ios)
    if (ios /= 0) stop "load_unformatted: cannot open file"
    read(unit) nread
    if (nread /= size) stop "load_unformatted: size mismatch"
    read(unit) arr
    close(unit)
  end subroutine load_unformatted

  ! --
  ! append_formatted  -- append to an existing text file
  ! --
  subroutine append_formatted(arr, size, filename)
    implicit none
    integer, intent(in)  :: size
    real,    intent(in)  :: arr(size)
    character(len=*), intent(in) :: filename
    integer :: unit, i

    open(newunit=unit, file=filename, status='old', position='append')
    do i = 1, size
      write(unit, *) arr(i)
    end do
    close(unit)
  end subroutine append_formatted

  ! --
  ! dump_with_header  -- text, first line is a comment
  ! --
  subroutine dump_with_header(arr, size, filename, header)
    implicit none
    integer, intent(in)  :: size
    real,    intent(in)  :: arr(size)
    character(len=*), intent(in) :: filename
    character(len=*), intent(in) :: header
    integer :: unit, i

    open(newunit=unit, file=filename, status='replace')
    write(unit, '(A)') "# " // trim(header)
    do i = 1, size
      write(unit, '(ES24.16)') arr(i)
    end do
    close(unit)
  end subroutine dump_with_header

  ! --
  ! dump_multicol  -- text, one row per record with ncol columns
  ! --
  subroutine dump_multicol(mat, nrow, ncol, filename)
    implicit none
    integer, intent(in)  :: nrow, ncol
    real,    intent(in)  :: mat(nrow,ncol)
    character(len=*), intent(in) :: filename
    integer :: unit, i, j

    open(newunit=unit, file=filename, status='replace')
    do i = 1, nrow
      write(unit, '(*(ES24.16,1X))') (mat(i,j), j = 1, ncol)
    end do
    close(unit)
  end subroutine dump_multicol

  ! --
  ! load_multicol  -- read rows of ncol values, list-directed
  ! --
  subroutine load_multicol(mat, nrow, ncol, filename)
    implicit none
    integer, intent(in)  :: nrow, ncol
    real,    intent(out) :: mat(nrow,ncol)
    character(len=*), intent(in) :: filename
    integer :: unit, i, ios

    open(newunit=unit, file=filename, status='old', iostat=ios)
    if (ios /= 0) stop "load_multicol: cannot open file"
    do i = 1, nrow
      read(unit, *, iostat=ios) mat(i,1:ncol)
      if (ios /= 0) stop "load_multicol: read error"
    end do
    close(unit)
  end subroutine load_multicol


  ! --
  ! inq_file_exists  -- logical function, uses INQUIRE
  ! --
  logical function inq_file_exists(filename)
    implicit none
    character(len=*), intent(in) :: filename
    logical :: there

    inquire(file=filename, exist=there)
    inq_file_exists = there
  end function inq_file_exists

  ! --
  ! inq_file_size  -- number of bytes in a file, 0 if not present
  ! --
  integer function inq_file_size(filename)
    implicit none
    character(len=*), intent(in) :: filename
    integer :: sz
    logical :: there

    inquire(file=filename, exist=there, size=sz)
    if (.not. there) then
      inq_file_size = 0
    else
      inq_file_size = sz
    end if
  end function inq_file_size

  !
  ! VERIFICATION HELPER
  !
  subroutine check_equal(a, b, size, label)
    implicit none
    integer, intent(in)  :: size
    real,    intent(in)  :: a(size), b(size)
    character(len=*), intent(in) :: label
    integer :: i
    logical :: ok

    ok = .true.
    do i = 1, size
      if (abs(a(i) - b(i)) > 1.0e-12 * max(1.0, abs(a(i)))) ok = .false.
    end do
    if (ok) then
      print '(A,A)', " [OK]   ", trim(label)
    else
      print '(A,A)', " [FAIL] ", trim(label)
    end if
  end subroutine check_equal

end program io_generic
