!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 29 Jul 2025 17:17
!
! Global module for multilevel_matrix generated by fgpt
MODULE module_global_multilevel_matrixmodule_global_multilevel_matrix_adj
  IMPLICIT NONE
  INTEGER, PARAMETER :: i_std = 4
  INTEGER, PARAMETER :: r_std = 8
  INTEGER(KIND = i_std), PARAMETER :: nice = 8
  INTEGER(KIND = i_std), PARAMETER :: ncirc = 3
  INTEGER(KIND = i_std), PARAMETER :: nsnow = 3
  INTEGER(KIND = i_std), PARAMETER :: nslm = 11
  INTEGER(KIND = i_std), PARAMETER :: nvm = 15
  INTEGER(KIND = i_std), PARAMETER :: nstm = 3
  INTEGER(KIND = i_std), PARAMETER :: kjpindex = 4717
  INTEGER :: ier
  INTEGER(KIND = i_std) :: ic0
  INTEGER(KIND = i_std) :: ic
  REAL(KIND = r_std) :: icr
  REAL(KIND = r_std) :: start_time
  REAL(KIND = r_std) :: stop_time
  INTEGER(KIND = i_std) :: nlevels_tot

  CONTAINS
  !  Differentiation of multilevel_matrix in reverse (adjoint) mode:
    !   gradient     of useful results: d t w fab fdn rs fup mu
    !   with respect to varying inputs: d t w fab fdn rs fup mu
    !   RW status of diff variables: d:incr t:incr w:incr fab:in-zero
    !                fdn:in-out rs:incr fup:in-out mu:incr
    !!
!& ==============================================================================================================================
    !! SUBROUTINE   : multilevel_matrix
    !!
    !>\BRIEF        : Multilevel matrix radiation transfer
    !!
    !! DESCRIPTION : Matrix radiation transfer where the mathematical representation
    !!               of radiative transfer involves using matrices to describe the transfer
    !!               of energy and properties of radiation within the medium.
    !!
    !! RECENT CHANGE(S): None
    !!
    !! MAIN OUTPUT VARIABLE(S): Upward flux, downward flux, and absorption
    !!
    !! REFERENCE(S) : K. Ardaneh et al. / Procedia Computer Science 255 (2025) 3–12
    !!
    !! FLOWCHART    :
    !! 1. Initialize Inputs
    !!
    !! Read vegetation canopy properties (LAI, reflectance, transmittance, scattering properties).
    !! Define incident solar flux, optical depth, and angular parameters.
    !! Set the number of layers nl.
    !!
    !! 2. Compute Two-Stream Coefficients
    !!
    !! Compute G(mu), K(mu), mu_bar, omega, omega_beta, and omega_beta0.
    !! Calculate two-stream approximation coefficients gamma1, gamma2, gamma3, gamma4.
    !!
    !! 3. Formulate the Matrix System
    !!
    !! Define the linear equations governing radiative transfer in multiple layers.
    !! Construct a tridiagonal system with coefficients e_l, d_l, f_l, g_l.
    !!
    !! 4. Apply Boundary Conditions
    !!
    !! At the top: Incoming downward flux.
    !! At the bottom: Upward flux determined by surface reflectance.
    !!
    !! 5. Solve Tridiagonal System
    !!
    !! Use the Thomas Algorithm for efficient computation.
    !! Compute flux amplitudes A_l, B_l for all layers.
    !!
    !! 6. Compute Final Radiative Fluxes
    !!
    !! Calculate downward and upward fluxes Fdn_l and Fup_l using solved amplitudes.
    !! Determine surface albedo, absorption (Fab), and transmission.
    !!
    !_
    !&
!& ==============================================================================================================================
    !==
    SUBROUTINE multilevel_matrix_b(nl, mu, mub, rs, rsb, t, tb, w, wb, d, db, fup, fupb, fdn, fdnb, fab, fabb)
    IMPLICIT NONE
    !! 0. Variables and parameter declaration
    !! 0.1 Input variables
    INTEGER, INTENT(IN) :: nl
    REAL(KIND = r_std), INTENT(IN) :: mu
    REAL(KIND = r_std) :: mub
    REAL(KIND = r_std), INTENT(IN) :: rs
    REAL(KIND = r_std) :: rsb
    REAL(KIND = r_std), INTENT(IN) :: w
    REAL(KIND = r_std) :: wb
    REAL(KIND = r_std), INTENT(IN) :: d
    REAL(KIND = r_std) :: db
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(IN) :: t
    REAL(KIND = r_std), DIMENSION(nlevels_tot) :: tb
    !! 0.2 Output variables
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(INOUT) :: fup
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(INOUT) :: fupb
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(INOUT) :: fdn
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(INOUT) :: fdnb
    REAL(KIND = r_std), DIMENSION(nlevels_tot) :: fab
    REAL(KIND = r_std), DIMENSION(nlevels_tot) :: fabb
    !! 0.3 Modified variables
    !! 0.4 Local variables
    REAL(KIND = r_std), DIMENSION(nl * 2) :: xn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: xnb
    REAL(KIND = r_std), DIMENSION(nl * 2) :: an
    REAL(KIND = r_std), DIMENSION(nl * 2) :: anb
    REAL(KIND = r_std), DIMENSION(nl * 2) :: bn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: bnb
    REAL(KIND = r_std), DIMENSION(nl * 2) :: cn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: cnb
    REAL(KIND = r_std), DIMENSION(nl * 2) :: gn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: gnb
    REAL(KIND = r_std), DIMENSION(2, nlevels_tot) :: data_pu
    REAL(KIND = r_std), DIMENSION(2, nlevels_tot) :: data_pub
    REAL(KIND = r_std), DIMENSION(11, nl) :: data_nl
    REAL(KIND = r_std), DIMENSION(11, nl) :: data_nlb
    REAL(KIND = r_std), DIMENSION(4) :: gam
    REAL(KIND = r_std), DIMENSION(4) :: gamb
    REAL(KIND = r_std), PARAMETER :: g = 0.5_r_std
    REAL(KIND = r_std), PARAMETER :: mubar = 1.0_r_std
    REAL(KIND = r_std) :: bs
    REAL(KIND = r_std) :: bsb
    REAL(KIND = r_std) :: lambda
    REAL(KIND = r_std) :: lambdab
    REAL(KIND = r_std) :: cap_gam
    REAL(KIND = r_std) :: cap_gamb
    REAL(KIND = r_std) :: exp_trm
    REAL(KIND = r_std) :: exp_trmb
    REAL(KIND = r_std) :: cpn
    REAL(KIND = r_std) :: cpnb
    REAL(KIND = r_std) :: cmn
    REAL(KIND = r_std) :: cmnb
    REAL(KIND = r_std) :: den
    REAL(KIND = r_std) :: denb
    REAL(KIND = r_std) :: exp_top
    REAL(KIND = r_std) :: exp_topb
    REAL(KIND = r_std) :: exp_bot
    REAL(KIND = r_std) :: exp_botb
    REAL(KIND = r_std) :: fdu
    REAL(KIND = r_std) :: fdub
    REAL(KIND = r_std) :: fdb
    REAL(KIND = r_std) :: fdbb
    INTEGER :: l
    INTEGER :: le
    INTEGER :: lo
    REAL(KIND = r_std) :: fspi
    REAL(KIND = r_std) :: fspib
    REAL(KIND = r_std) :: mu0
    REAL(KIND = r_std) :: mu0b
    REAL(KIND = r_std) :: k
    REAL(KIND = r_std) :: kb
    REAL(KIND = r_std) :: beta
    REAL(KIND = r_std) :: betab
    REAL(KIND = r_std) :: beta0
    REAL(KIND = r_std) :: beta0b
    INTRINSIC :: SQRT
    INTRINSIC :: MIN
    INTRINSIC :: EXP
    REAL(KIND = r_std) :: min1
    REAL(KIND = r_std) :: min1b
    REAL(KIND = r_std) :: min2
    REAL(KIND = r_std) :: min2b
    REAL(KIND = r_std) :: min3
    REAL(KIND = r_std) :: min3b
    REAL(KIND = r_std) :: tempb
    REAL(KIND = r_std) :: temp
    REAL(KIND = r_std) :: tempb0
    REAL(KIND = r_std) :: temp0
    REAL(KIND = r_std) :: tempb1
    INTEGER*4 :: branch
    !_
    !&
!& ==============================================================================================================================
    !==
    k = g / mu
    ! K in Eq. (12)
    beta0 = 0.5_r_std / w * (w + 2.0_r_std * d * mu / 3.0_r_std)
    ! β0 Eq. (12)
    beta = 0.5_r_std / w * (w + d / 3.0_r_std)
    ! β in Eq. (12)
    ! Gamma coefficients (γ₁, γ₂, γ₃, and γ₄ = 1 − γ₃) according to the δ-methods
    gam(1) = 1.0_r_std - (1.0_r_std - beta) * w
    gam(2) = w * beta
    gam(3) = beta0
    gam(4) = 1.0_r_std - gam(3)
    ! Transformation of the two-stream equations for vegetation
    mu0 = 1.0_r_std / k
    fspi = 1.0_r_std / mu0
    data_nl(1, :) = t(nl : 1 : - 1)
    ! Δτₗ in Fig. 1
    lambda = SQRT(gam(1) ** 2 - gam(2) ** 2)
    ! λ in Eq. (3)
    cap_gam = gam(2) / (gam(1) + lambda)
    ! Γ in Eq. (3)
    ! Cumulative optical depths (τc)
    data_pu(1, 1) = 0.0_r_std
    DO l = 2, nlevels_tot
      data_pu(1, l) = data_pu(1, l - 1) + data_nl(1, l - 1)
    END DO
    fdb = 0.0_r_std
    ! diffuse flux at top
    data_pu(2, 1) = mu0 * fspi
    ! direct flux at top
      DO l = 1, nl
      IF (lambda * data_nl(1, l) .GT. 30.0_r_std) THEN
        CALL pushreal8(min1)
        min1 = 30.0_r_std
        CALL pushcontrol1b(0)
      ELSE
        CALL pushreal8(min1)
        min1 = lambda * data_nl(1, l)
        CALL pushcontrol1b(1)
      END IF
      ! Eqs. (8)
      CALL pushreal8(exp_trm)
      exp_trm = EXP(- min1)
      CALL pushreal8(data_nl(2, l))
      data_nl(2, l) = 1.0_r_std + cap_gam * exp_trm
      CALL pushreal8(data_nl(3, l))
      data_nl(3, l) = 1.0_r_std - cap_gam * exp_trm
      CALL pushreal8(data_nl(4, l))
      data_nl(4, l) = cap_gam + exp_trm
      CALL pushreal8(data_nl(5, l))
      data_nl(5, l) = cap_gam - exp_trm
      ! Exponential terms in Eq. (3)
      cpn = w * fspi * ((gam(1) - 1.0_r_std / mu0) * gam(3) + gam(4) * gam(2))
      cmn = w * fspi * ((gam(1) + 1.0_r_std / mu0) * gam(4) + gam(2) * gam(3))
      den = lambda ** 2 - 1.0_r_std / mu0 ** 2
      IF (data_pu(1, l) / mu0 .GT. 30.0_r_std) THEN
        CALL pushreal8(min2)
        min2 = 30.0_r_std
        CALL pushcontrol1b(0)
      ELSE
        CALL pushreal8(min2)
        min2 = data_pu(1, l) / mu0
        CALL pushcontrol1b(1)
      END IF
      CALL pushreal8(exp_top)
      exp_top = EXP(- min2)
      IF (data_nl(1, l) / mu0 .GT. 30.0_r_std) THEN
        CALL pushreal8(min3)
        min3 = 30.0_r_std
        CALL pushcontrol1b(0)
      ELSE
        CALL pushreal8(min3)
        min3 = data_nl(1, l) / mu0
        CALL pushcontrol1b(1)
      END IF
      CALL pushreal8(exp_bot)
      exp_bot = exp_top * EXP(- min3)
      CALL pushreal8(data_pu(2, l + 1))
      data_pu(2, l + 1) = mu0 * fspi * exp_bot
      CALL pushreal8(data_nl(6, l))
      data_nl(6, l) = exp_top * cpn / den
      CALL pushreal8(data_nl(7, l))
      data_nl(7, l) = exp_bot * cpn / den
      CALL pushreal8(data_nl(8, l))
      data_nl(8, l) = exp_top * cmn / den
      CALL pushreal8(data_nl(9, l))
      data_nl(9, l) = exp_bot * cmn / den
    END DO
    ! Boundary conditions at the top  of the structure.
    bs = rs * data_pu(2, nlevels_tot)
    an(1) = 0.0_r_std
    bn(1) = data_nl(2, 1)
    cn(1) = - data_nl(3, 1)
    gn(1) = fdb - data_nl(8, 1)
    ! Matrix of coefficients in Eqs. (9)
      DO l = 1, nl - 1
      le = 2 * l
      lo = 2 * l + 1
      an(le) = data_nl(3, l + 1) * data_nl(2, l) - data_nl(5, l + 1) * data_nl(4, l)
      an(lo) = data_nl(3, l) * data_nl(4, l) - data_nl(5, l) * data_nl(2, l)
      bn(le) = data_nl(3, l) * data_nl(3, l + 1) - data_nl(5, l) * data_nl(5, l + 1)
      bn(lo) = data_nl(2, l) * data_nl(2, l + 1) - data_nl(4, l) * data_nl(4, l + 1)
      cn(le) = data_nl(2, l + 1) * data_nl(5, l + 1) - data_nl(3, l + 1) * data_nl(4, l + 1)
      cn(lo) = data_nl(4, l) * data_nl(5, l + 1) - data_nl(2, l) * data_nl(3, l + 1)
      gn(le) = data_nl(3, l + 1) * (data_nl(6, l + 1) - data_nl(7, l)) - data_nl(5, l + 1) * (data_nl(8, l + 1) - data_nl(9, l))
      gn(lo) = data_nl(4, l) * (data_nl(6, l + 1) - data_nl(7, l)) + data_nl(2, l) * (data_nl(9, l) - data_nl(8, l + 1))
    END DO
    ! Boundary conditions at the bottom of the structure.
    l = 2 * nl
    an(l) = data_nl(2, nl) - rs * data_nl(4, nl)
    bn(l) = data_nl(3, nl) - rs * data_nl(5, nl)
    cn(l) = 0.0_r_std
    gn(l) = bs - data_nl(7, nl) + rs * data_nl(9, nl)
    CALL pushreal8array(xn, nl * 2)
    CALL pushreal8array(gn, nl * 2)
    CALL pushreal8array(bn, nl * 2)
    CALL trdiag(l, an, bn, cn, gn, xn)
    ! Matrix solutions unpacking
    CALL pushreal8array(data_nl(10, :), nl)
    data_nl(10, :) = xn(1 : l : 2)
    CALL pushreal8array(data_nl(11, :), nl)
    data_nl(11, :) = xn(2 : l : 2)
    ! Calculation of flux
    CALL pushinteger4(l)
    fdnb(nlevels_tot : 2 : - 1) = fdnb(nlevels_tot : 2 : - 1) + fabb(nl : 1 : - 1)
    fupb(nlevels_tot : 2 : - 1) = fupb(nlevels_tot : 2 : - 1) - fabb(nl : 1 : - 1)
    fupb(nl : 1 : - 1) = fupb(nl : 1 : - 1) + fabb(nl : 1 : - 1)
    fdnb(nl : 1 : - 1) = fdnb(nl : 1 : - 1) - fabb(nl : 1 : - 1)
    data_nlb = 0.0_8
    data_pub = 0.0_8
    DO l = nl, 1, - 1
      le = nlevels_tot - l
      fdbb = fdnb(le)
      data_pub(2, l + 1) = data_pub(2, l + 1) + fdnb(le)
      fdnb(le) = 0.0_8
      data_nlb(4, l) = data_nlb(4, l) + data_nl(10, l) * fdbb
      data_nlb(5, l) = data_nlb(5, l) + data_nl(11, l) * fdbb
      data_nlb(9, l) = data_nlb(9, l) + fdbb
      fdub = fupb(le)
      data_nlb(10, l) = data_nlb(10, l) + data_nl(4, l) * fdbb + data_nl(2, l) * fdub
      data_nlb(11, l) = data_nlb(11, l) + data_nl(5, l) * fdbb + data_nl(3, l) * fdub
      fupb(le) = 0.0_8
      data_nlb(2, l) = data_nlb(2, l) + data_nl(10, l) * fdub
      data_nlb(3, l) = data_nlb(3, l) + data_nl(11, l) * fdub
      data_nlb(7, l) = data_nlb(7, l) + fdub
    END DO
    CALL popinteger4(l)
    data_pub(2, 1) = data_pub(2, 1) + fdnb(nlevels_tot)
    fdnb(nlevels_tot) = 0.0_8
    fdub = fupb(nlevels_tot)
    fupb(nlevels_tot) = 0.0_8
    data_nlb(10, 1) = data_nlb(10, 1) + data_nl(4, 1) * fdub
    data_nlb(4, 1) = data_nlb(4, 1) + data_nl(10, 1) * fdub
    data_nlb(11, 1) = data_nlb(11, 1) - data_nl(5, 1) * fdub
    data_nlb(5, 1) = data_nlb(5, 1) - data_nl(11, 1) * fdub
    data_nlb(6, 1) = data_nlb(6, 1) + fdub
    l = 2 * nl
    xnb = 0.0_8
    CALL popreal8array(data_nl(11, :), nl)
    xnb(2 : l : 2) = xnb(2 : l : 2) + data_nlb(11, :)
    data_nlb(11, :) = 0.0_8
    CALL popreal8array(data_nl(10, :), nl)
    xnb(1 : l : 2) = xnb(1 : l : 2) + data_nlb(10, :)
    data_nlb(10, :) = 0.0_8
    CALL popreal8array(bn, nl * 2)
    CALL popreal8array(gn, nl * 2)
    CALL popreal8array(xn, nl * 2)
    CALL trdiag_b(l, an, anb, bn, bnb, cn, cnb, gn, gnb, xn, xnb)
    bsb = gnb(l)
    data_nlb(7, nl) = data_nlb(7, nl) - gnb(l)
    rsb = rsb + data_nl(9, nl) * gnb(l) - data_nl(5, nl) * bnb(l) - data_nl(4, nl) * anb(l)
    data_nlb(9, nl) = data_nlb(9, nl) + rs * gnb(l)
    gnb(l) = 0.0_8
    cnb(l) = 0.0_8
    data_nlb(3, nl) = data_nlb(3, nl) + bnb(l)
    data_nlb(5, nl) = data_nlb(5, nl) - rs * bnb(l)
    bnb(l) = 0.0_8
    data_nlb(2, nl) = data_nlb(2, nl) + anb(l)
    data_nlb(4, nl) = data_nlb(4, nl) - rs * anb(l)
    anb(l) = 0.0_8
    DO l = nl - 1, 1, - 1
      lo = 2 * l + 1
      data_nlb(4, l) = data_nlb(4, l) + (data_nl(6, l + 1) - data_nl(7, l)) * gnb(lo) + data_nl(5, l + 1) * cnb(lo) + data_nl(3, &
&l) * anb(lo) - data_nl(4, l + 1) * bnb(lo)
      tempb1 = data_nl(4, l) * gnb(lo)
      data_nlb(2, l) = data_nlb(2, l) + (data_nl(9, l) - data_nl(8, l + 1)) * gnb(lo) + data_nl(2, l + 1) * bnb(lo) - data_nl(3, l &
&+ 1) * cnb(lo) - data_nl(5, l) * anb(lo)
      tempb0 = data_nl(2, l) * gnb(lo)
      gnb(lo) = 0.0_8
      data_nlb(9, l) = data_nlb(9, l) + tempb0
      data_nlb(8, l + 1) = data_nlb(8, l + 1) - tempb0
      data_nlb(6, l + 1) = data_nlb(6, l + 1) + tempb1
      data_nlb(7, l) = data_nlb(7, l) - tempb1
      le = 2 * l
      data_nlb(3, l + 1) = data_nlb(3, l + 1) + (data_nl(6, l + 1) - data_nl(7, l)) * gnb(le) - data_nl(2, l) * cnb(lo)
      tempb1 = data_nl(3, l + 1) * gnb(le)
      data_nlb(5, l + 1) = data_nlb(5, l + 1) + data_nl(4, l) * cnb(lo) - (data_nl(8, l + 1) - data_nl(9, l)) * gnb(le)
      tempb0 = - (data_nl(5, l + 1) * gnb(le))
      gnb(le) = 0.0_8
      data_nlb(8, l + 1) = data_nlb(8, l + 1) + tempb0
      data_nlb(9, l) = data_nlb(9, l) - tempb0
      data_nlb(6, l + 1) = data_nlb(6, l + 1) + tempb1
      data_nlb(7, l) = data_nlb(7, l) - tempb1
      cnb(lo) = 0.0_8
      data_nlb(2, l + 1) = data_nlb(2, l + 1) + data_nl(5, l + 1) * cnb(le) + data_nl(2, l) * bnb(lo)
      data_nlb(4, l + 1) = data_nlb(4, l + 1) - data_nl(3, l + 1) * cnb(le) - data_nl(4, l) * bnb(lo)
      bnb(lo) = 0.0_8
      data_nlb(3, l) = data_nlb(3, l) + data_nl(3, l + 1) * bnb(le) + data_nl(4, l) * anb(lo)
      data_nlb(5, l) = data_nlb(5, l) - data_nl(5, l + 1) * bnb(le) - data_nl(2, l) * anb(lo)
      anb(lo) = 0.0_8
      data_nlb(5, l + 1) = data_nlb(5, l + 1) + data_nl(2, l + 1) * cnb(le) - data_nl(5, l) * bnb(le) - data_nl(4, l) * anb(le)
      data_nlb(3, l + 1) = data_nlb(3, l + 1) + data_nl(3, l) * bnb(le) - data_nl(4, l + 1) * cnb(le) + data_nl(2, l) * anb(le)
      cnb(le) = 0.0_8
      bnb(le) = 0.0_8
      data_nlb(2, l) = data_nlb(2, l) + data_nl(3, l + 1) * anb(le)
      data_nlb(4, l) = data_nlb(4, l) - data_nl(5, l + 1) * anb(le)
      anb(le) = 0.0_8
    END DO
    data_nlb(8, 1) = data_nlb(8, 1) - gnb(1)
    data_nlb(3, 1) = data_nlb(3, 1) - cnb(1)
    data_nlb(2, 1) = data_nlb(2, 1) + bnb(1)
    rsb = rsb + data_pu(2, nlevels_tot) * bsb
    data_pub(2, nlevels_tot) = data_pub(2, nlevels_tot) + rs * bsb
    mu0b = 0.0_8
    lambdab = 0.0_8
    cap_gamb = 0.0_8
    fspib = 0.0_8
    gamb = 0.0_8
    DO l = nl, 1, - 1
      cmn = w * fspi * ((gam(1) + 1.0_r_std / mu0) * gam(4) + gam(2) * gam(3))
      den = lambda ** 2 - 1.0_r_std / mu0 ** 2
      CALL popreal8(data_nl(9, l))
      tempb1 = data_nlb(9, l) / den
      data_nlb(9, l) = 0.0_8
      exp_botb = cmn * tempb1
      cmnb = exp_bot * tempb1
      denb = - (exp_bot * cmn * tempb1 / den)
      CALL popreal8(data_nl(8, l))
      tempb1 = data_nlb(8, l) / den
      data_nlb(8, l) = 0.0_8
      exp_topb = cmn * tempb1
      cmnb = cmnb + exp_top * tempb1
      denb = denb - exp_top * cmn * tempb1 / den
      cpn = w * fspi * ((gam(1) - 1.0_r_std / mu0) * gam(3) + gam(4) * gam(2))
      CALL popreal8(data_nl(7, l))
      tempb1 = data_nlb(7, l) / den
      data_nlb(7, l) = 0.0_8
      exp_botb = exp_botb + cpn * tempb1 + mu0 * fspi * data_pub(2, l + 1)
      cpnb = exp_bot * tempb1
      denb = denb - exp_bot * cpn * tempb1 / den
      CALL popreal8(data_nl(6, l))
      tempb1 = data_nlb(6, l) / den
      data_nlb(6, l) = 0.0_8
      exp_topb = exp_topb + cpn * tempb1 + EXP(- min3) * exp_botb
      cpnb = cpnb + exp_top * tempb1
      denb = denb - exp_top * cpn * tempb1 / den
      CALL popreal8(data_pu(2, l + 1))
      mu0b = mu0b + fspi * exp_bot * data_pub(2, l + 1)
      fspib = fspib + mu0 * exp_bot * data_pub(2, l + 1)
      data_pub(2, l + 1) = 0.0_8
      CALL popreal8(exp_bot)
      min3b = - (EXP(- min3) * exp_top * exp_botb)
      CALL popcontrol1b(branch)
      IF (branch .EQ. 0) THEN
        CALL popreal8(min3)
      ELSE
        CALL popreal8(min3)
        data_nlb(1, l) = data_nlb(1, l) + min3b / mu0
        mu0b = mu0b - data_nl(1, l) * min3b / mu0 ** 2
      END IF
      CALL popreal8(exp_top)
      min2b = - (EXP(- min2) * exp_topb)
      CALL popcontrol1b(branch)
      IF (branch .EQ. 0) THEN
        CALL popreal8(min2)
      ELSE
        CALL popreal8(min2)
        data_pub(1, l) = data_pub(1, l) + min2b / mu0
        mu0b = mu0b - data_pu(1, l) * min2b / mu0 ** 2
      END IF
      tempb1 = w * fspi * cpnb
      temp = 1.0 / mu0
      tempb = w * fspi * cmnb
      temp0 = 1.0 / mu0
      lambdab = lambdab + 2 * lambda * denb
      mu0b = mu0b + 2 * denb / mu0 ** 3 + temp * gam(3) * tempb1 / mu0 - temp0 * gam(4) * tempb / mu0
      tempb0 = ((gam(1) + temp0) * gam(4) + gam(2) * gam(3)) * cmnb
      gamb(1) = gamb(1) + gam(4) * tempb + gam(3) * tempb1
      gamb(4) = gamb(4) + (gam(1) + temp0) * tempb + gam(2) * tempb1
      gamb(2) = gamb(2) + gam(3) * tempb + gam(4) * tempb1
      gamb(3) = gamb(3) + gam(2) * tempb + (gam(1) - temp) * tempb1
      tempb = ((gam(1) - temp) * gam(3) + gam(4) * gam(2)) * cpnb
      wb = wb + fspi * tempb0 + fspi * tempb
      fspib = fspib + w * tempb0 + w * tempb
      CALL popreal8(data_nl(5, l))
      cap_gamb = cap_gamb + data_nlb(5, l) + data_nlb(4, l) + exp_trm * data_nlb(2, l) - exp_trm * data_nlb(3, l)
      exp_trmb = data_nlb(4, l) - data_nlb(5, l) + cap_gam * data_nlb(2, l) - cap_gam * data_nlb(3, l)
      data_nlb(5, l) = 0.0_8
      CALL popreal8(data_nl(4, l))
      data_nlb(4, l) = 0.0_8
      CALL popreal8(data_nl(3, l))
      data_nlb(3, l) = 0.0_8
      CALL popreal8(data_nl(2, l))
      data_nlb(2, l) = 0.0_8
      CALL popreal8(exp_trm)
      min1b = - (EXP(- min1) * exp_trmb)
      CALL popcontrol1b(branch)
      IF (branch .EQ. 0) THEN
        CALL popreal8(min1)
      ELSE
        CALL popreal8(min1)
        lambdab = lambdab + data_nl(1, l) * min1b
        data_nlb(1, l) = data_nlb(1, l) + lambda * min1b
      END IF
    END DO
    mu0b = mu0b + fspi * data_pub(2, 1)
    fspib = fspib + mu0 * data_pub(2, 1)
    data_pub(2, 1) = 0.0_8
    DO l = nlevels_tot, 2, - 1
      data_pub(1, l - 1) = data_pub(1, l - 1) + data_pub(1, l)
      data_nlb(1, l - 1) = data_nlb(1, l - 1) + data_pub(1, l)
      data_pub(1, l) = 0.0_8
    END DO
    tempb = cap_gamb / (gam(1) + lambda)
    gamb(2) = gamb(2) + tempb
    tempb0 = - (gam(2) * tempb / (gam(1) + lambda))
    lambdab = lambdab + tempb0
    IF (gam(1) ** 2 - gam(2) ** 2 .EQ. 0.0) THEN
      tempb = 0.0_8
    ELSE
      tempb = lambdab / (2.0 * SQRT(gam(1) ** 2 - gam(2) ** 2))
    END IF
    gamb(1) = gamb(1) + tempb0 + 2 * gam(1) * tempb
    gamb(2) = gamb(2) - 2 * gam(2) * tempb
    tb(nl : 1 : - 1) = tb(nl : 1 : - 1) + data_nlb(1, :)
    mu0b = mu0b - fspib / mu0 ** 2
    kb = - (mu0b / k ** 2)
    gamb(3) = gamb(3) - gamb(4)
    gamb(4) = 0.0_8
    beta0b = gamb(3)
    gamb(3) = 0.0_8
    betab = w * gamb(2) + w * gamb(1)
    tempb = 0.5_r_std * betab / w
    wb = wb + beta * gamb(2) + (1.0 - (w + d / 3.0_r_std) / w) * tempb - (1.0_r_std - beta) * gamb(1)
    gamb(2) = 0.0_8
    db = db + tempb / 3.0_r_std
    tempb = 0.5_r_std * beta0b / w
    wb = wb + (1.0 - (w + 2.0_r_std * (d / 3.0_r_std * mu)) / w) * tempb
    db = db + mu * 2.0_r_std * tempb / 3.0_r_std
    mub = mub + d * 2.0_r_std * tempb / 3.0_r_std - g * kb / mu ** 2
    fabb = 0.0_8
  END SUBROUTINE multilevel_matrix_b

    !!
!& ==============================================================================================================================
    !! SUBROUTINE   : multilevel_matrix
    !!
    !>\BRIEF        : Multilevel matrix radiation transfer
    !!
    !! DESCRIPTION : Matrix radiation transfer where the mathematical representation
    !!               of radiative transfer involves using matrices to describe the transfer
    !!               of energy and properties of radiation within the medium.
    !!
    !! RECENT CHANGE(S): None
    !!
    !! MAIN OUTPUT VARIABLE(S): Upward flux, downward flux, and absorption
    !!
    !! REFERENCE(S) : K. Ardaneh et al. / Procedia Computer Science 255 (2025) 3–12
    !!
    !! FLOWCHART    :
    !! 1. Initialize Inputs
    !!
    !! Read vegetation canopy properties (LAI, reflectance, transmittance, scattering properties).
    !! Define incident solar flux, optical depth, and angular parameters.
    !! Set the number of layers nl.
    !!
    !! 2. Compute Two-Stream Coefficients
    !!
    !! Compute G(mu), K(mu), mu_bar, omega, omega_beta, and omega_beta0.
    !! Calculate two-stream approximation coefficients gamma1, gamma2, gamma3, gamma4.
    !!
    !! 3. Formulate the Matrix System
    !!
    !! Define the linear equations governing radiative transfer in multiple layers.
    !! Construct a tridiagonal system with coefficients e_l, d_l, f_l, g_l.
    !!
    !! 4. Apply Boundary Conditions
    !!
    !! At the top: Incoming downward flux.
    !! At the bottom: Upward flux determined by surface reflectance.
    !!
    !! 5. Solve Tridiagonal System
    !!
    !! Use the Thomas Algorithm for efficient computation.
    !! Compute flux amplitudes A_l, B_l for all layers.
    !!
    !! 6. Compute Final Radiative Fluxes
    !!
    !! Calculate downward and upward fluxes Fdn_l and Fup_l using solved amplitudes.
    !! Determine surface albedo, absorption (Fab), and transmission.
    !!
    !_
    !&
!& ==============================================================================================================================
    !==
    SUBROUTINE multilevel_matrix(nl, mu, rs, t, w, d, fup, fdn, fab)
    IMPLICIT NONE
    !! 0. Variables and parameter declaration
    !! 0.1 Input variables
    INTEGER, INTENT(IN) :: nl
    REAL(KIND = r_std), INTENT(IN) :: mu
    REAL(KIND = r_std), INTENT(IN) :: rs
    REAL(KIND = r_std), INTENT(IN) :: w
    REAL(KIND = r_std), INTENT(IN) :: d
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(IN) :: t
    !! 0.2 Output variables
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(INOUT) :: fup
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(INOUT) :: fdn
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(OUT) :: fab
    !! 0.3 Modified variables
    !! 0.4 Local variables
    REAL(KIND = r_std), DIMENSION(nl * 2) :: xn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: an
    REAL(KIND = r_std), DIMENSION(nl * 2) :: bn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: cn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: gn
    REAL(KIND = r_std), DIMENSION(2, nlevels_tot) :: data_pu
    REAL(KIND = r_std), DIMENSION(11, nl) :: data_nl
    REAL(KIND = r_std), DIMENSION(4) :: gam
    REAL(KIND = r_std), PARAMETER :: g = 0.5_r_std
    REAL(KIND = r_std), PARAMETER :: mubar = 1.0_r_std
    REAL(KIND = r_std) :: bs
    REAL(KIND = r_std) :: lambda
    REAL(KIND = r_std) :: cap_gam
    REAL(KIND = r_std) :: exp_trm
    REAL(KIND = r_std) :: cpn
    REAL(KIND = r_std) :: cmn
    REAL(KIND = r_std) :: den
    REAL(KIND = r_std) :: exp_top
    REAL(KIND = r_std) :: exp_bot
    REAL(KIND = r_std) :: fdu
    REAL(KIND = r_std) :: fdb
    INTEGER :: l
    INTEGER :: le
    INTEGER :: lo
    REAL(KIND = r_std) :: fspi
    REAL(KIND = r_std) :: mu0
    REAL(KIND = r_std) :: k
    REAL(KIND = r_std) :: beta
    REAL(KIND = r_std) :: beta0
    INTRINSIC :: SQRT
    INTRINSIC :: MIN
    INTRINSIC :: EXP
    REAL(KIND = r_std) :: min1
    REAL(KIND = r_std) :: min2
    REAL(KIND = r_std) :: min3
    !_
    !&
!& ==============================================================================================================================
    !==
    fab(:) = 0.0_r_std
    k = g / mu
    ! K in Eq. (12)
    beta0 = 0.5_r_std / w * (w + 2.0_r_std * d * mu / 3.0_r_std)
    ! β0 Eq. (12)
    beta = 0.5_r_std / w * (w + d / 3.0_r_std)
    ! β in Eq. (12)
    ! Gamma coefficients (γ₁, γ₂, γ₃, and γ₄ = 1 − γ₃) according to the δ-methods
    gam(1) = 1.0_r_std - (1.0_r_std - beta) * w
    gam(2) = w * beta
    gam(3) = beta0
    gam(4) = 1.0_r_std - gam(3)
    ! Transformation of the two-stream equations for vegetation
    mu0 = 1.0_r_std / k
    fspi = 1.0_r_std / mu0
    data_nl(1, :) = t(nl : 1 : - 1)
    ! Δτₗ in Fig. 1
    lambda = SQRT(gam(1) ** 2 - gam(2) ** 2)
    ! λ in Eq. (3)
    cap_gam = gam(2) / (gam(1) + lambda)
    ! Γ in Eq. (3)
    ! Cumulative optical depths (τc)
    data_pu(1, 1) = 0.0_r_std
    DO l = 2, nlevels_tot
      data_pu(1, l) = data_pu(1, l - 1) + data_nl(1, l - 1)
    END DO
    fdb = 0.0_r_std
    ! diffuse flux at top
    data_pu(2, 1) = mu0 * fspi
    ! direct flux at top
      DO l = 1, nl
      IF (lambda * data_nl(1, l) .GT. 30.0_r_std) THEN
        min1 = 30.0_r_std
      ELSE
        min1 = lambda * data_nl(1, l)
      END IF
      ! Eqs. (8)
      exp_trm = EXP(- min1)
      data_nl(2, l) = 1.0_r_std + cap_gam * exp_trm
      data_nl(3, l) = 1.0_r_std - cap_gam * exp_trm
      data_nl(4, l) = cap_gam + exp_trm
      data_nl(5, l) = cap_gam - exp_trm
      ! Exponential terms in Eq. (3)
      cpn = w * fspi * ((gam(1) - 1.0_r_std / mu0) * gam(3) + gam(4) * gam(2))
      cmn = w * fspi * ((gam(1) + 1.0_r_std / mu0) * gam(4) + gam(2) * gam(3))
      den = lambda ** 2 - 1.0_r_std / mu0 ** 2
      IF (data_pu(1, l) / mu0 .GT. 30.0_r_std) THEN
        min2 = 30.0_r_std
      ELSE
        min2 = data_pu(1, l) / mu0
      END IF
      exp_top = EXP(- min2)
      IF (data_nl(1, l) / mu0 .GT. 30.0_r_std) THEN
        min3 = 30.0_r_std
      ELSE
        min3 = data_nl(1, l) / mu0
      END IF
      exp_bot = exp_top * EXP(- min3)
      data_pu(2, l + 1) = mu0 * fspi * exp_bot
      data_nl(6, l) = exp_top * cpn / den
      data_nl(7, l) = exp_bot * cpn / den
      data_nl(8, l) = exp_top * cmn / den
      data_nl(9, l) = exp_bot * cmn / den
    END DO
    ! Boundary conditions at the top  of the structure.
    bs = rs * data_pu(2, nlevels_tot)
    an(1) = 0.0_r_std
    bn(1) = data_nl(2, 1)
    cn(1) = - data_nl(3, 1)
    gn(1) = fdb - data_nl(8, 1)
    ! Matrix of coefficients in Eqs. (9)
      DO l = 1, nl - 1
      le = 2 * l
      lo = 2 * l + 1
      an(le) = data_nl(3, l + 1) * data_nl(2, l) - data_nl(5, l + 1) * data_nl(4, l)
      an(lo) = data_nl(3, l) * data_nl(4, l) - data_nl(5, l) * data_nl(2, l)
      bn(le) = data_nl(3, l) * data_nl(3, l + 1) - data_nl(5, l) * data_nl(5, l + 1)
      bn(lo) = data_nl(2, l) * data_nl(2, l + 1) - data_nl(4, l) * data_nl(4, l + 1)
      cn(le) = data_nl(2, l + 1) * data_nl(5, l + 1) - data_nl(3, l + 1) * data_nl(4, l + 1)
      cn(lo) = data_nl(4, l) * data_nl(5, l + 1) - data_nl(2, l) * data_nl(3, l + 1)
      gn(le) = data_nl(3, l + 1) * (data_nl(6, l + 1) - data_nl(7, l)) - data_nl(5, l + 1) * (data_nl(8, l + 1) - data_nl(9, l))
      gn(lo) = data_nl(4, l) * (data_nl(6, l + 1) - data_nl(7, l)) + data_nl(2, l) * (data_nl(9, l) - data_nl(8, l + 1))
    END DO
    ! Boundary conditions at the bottom of the structure.
    l = 2 * nl
    an(l) = data_nl(2, nl) - rs * data_nl(4, nl)
    bn(l) = data_nl(3, nl) - rs * data_nl(5, nl)
    cn(l) = 0.0_r_std
    gn(l) = bs - data_nl(7, nl) + rs * data_nl(9, nl)
    CALL trdiag(l, an, bn, cn, gn, xn)
    ! Matrix solutions unpacking
    data_nl(10, :) = xn(1 : l : 2)
    data_nl(11, :) = xn(2 : l : 2)
    ! Calculation of flux
    fdu = data_nl(10, 1) * data_nl(4, 1) - data_nl(11, 1) * data_nl(5, 1) + data_nl(6, 1)
    fup(nlevels_tot) = fdu
    fdn(nlevels_tot) = fdb + data_pu(2, 1)
    DO l = 1, nl
      le = nlevels_tot - l
      fdu = data_nl(10, l) * data_nl(2, l) + data_nl(11, l) * data_nl(3, l) + data_nl(7, l)
      fup(le) = fdu
      fdb = data_nl(10, l) * data_nl(4, l) + data_nl(11, l) * data_nl(5, l) + data_nl(9, l)
      fdn(le) = fdb + data_pu(2, l + 1)
    END DO
    ! Calculation of absorption
    fab(nl : 1 : - 1) = fdn(nlevels_tot : 2 : - 1) - fup(nlevels_tot : 2 : - 1) - (fdn(nl : 1 : - 1) - fup(nl : 1 : - 1))
  END SUBROUTINE multilevel_matrix

    !  Differentiation of trdiag in reverse (adjoint) mode:
    !   gradient     of useful results: x
    !   with respect to varying inputs: g a b c
    !!
!& ==============================================================================================================================
    !! SUBROUTINE   : trdiag
    !!
    !>\BRIEF        : Tridiagonal matrix algorithm solver using Thomas algorithm
    !!                solves Ax = g where A is a tridiagonal matrix consisting of vectors a, b, c
    !! DESCRIPTION : The Thomas algorithm, also known as the tridiagonal matrix algorithm,
    !!               is an efficient method for solving systems of linear equations with
    !!               a tridiagonal coefficient matrix.
    !!               n - number of equations
    !!               a - sub-diagonal (means it is the diagonal below the main diagonal)
    !!               b - the main diagonal
    !!               c - sup-diagonal (means it is the diagonal above the main diagonal)
    !!               g - right part
    !!               x - the answer
    !!
    !! RECENT CHANGE(S): None
    !!
    !! MAIN OUTPUT VARIABLE(S): Matrix of solutions x
    !!
    !! REFERENCE(S) : Joe D. Hoffman, 2001, Numerical Methods for Engineers and Scientists, Second Edition
    !!
    !! FLOWCHART    : None
    !_
    !&
!& ==============================================================================================================================
    !==
    SUBROUTINE trdiag_b(n, a, ab, b, bb, c, cb, g, gb, x, xb)
    IMPLICIT NONE
    !! 0. Variables and parameter declaration
    !! 0.1 Input variables
    INTEGER, INTENT(IN) :: n
    REAL(KIND = r_std), DIMENSION(n), INTENT(IN) :: a
    REAL(KIND = r_std), DIMENSION(n) :: ab
    REAL(KIND = r_std), DIMENSION(n), INTENT(IN) :: c
    REAL(KIND = r_std), DIMENSION(n) :: cb
    !! 0.2 Output variables
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: x
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: xb
    !! 0.3 Modified variables
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: b
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: bb
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: g
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: gb
    !! 0.4 Local variables
    INTEGER :: i
    REAL(KIND = r_std) :: t
    REAL(KIND = r_std) :: tb
    REAL(KIND = r_std) :: tempb
    !_
    !&
!& ==============================================================================================================================
    !==
    ! Forward elimination phase
    DO i = 2, n
      CALL pushreal8(t)
      t = a(i) / b(i - 1)
      CALL pushreal8(b(i))
      b(i) = b(i) - c(i - 1) * t
      CALL pushreal8(g(i))
      g(i) = g(i) - g(i - 1) * t
    END DO
    ! Backward substitution phase
    x(n) = g(n) / b(n)
    DO i = n - 1, 1, - 1
      CALL pushreal8(x(i))
      x(i) = (g(i) - c(i) * x(i + 1)) / b(i)
    END DO
    gb = 0.0_8
    bb = 0.0_8
    cb = 0.0_8
    DO i = 1, n - 1, 1
      CALL popreal8(x(i))
      tempb = xb(i) / b(i)
      xb(i) = 0.0_8
      gb(i) = gb(i) + tempb
      cb(i) = cb(i) - x(i + 1) * tempb
      xb(i + 1) = xb(i + 1) - c(i) * tempb
      bb(i) = bb(i) - (g(i) - c(i) * x(i + 1)) * tempb / b(i)
    END DO
    tempb = xb(n) / b(n)
    gb(n) = gb(n) + tempb
    bb(n) = bb(n) - g(n) * tempb / b(n)
    ab = 0.0_8
    DO i = n, 2, - 1
      CALL popreal8(g(i))
      gb(i - 1) = gb(i - 1) - t * gb(i)
      tb = - (g(i - 1) * gb(i)) - c(i - 1) * bb(i)
      CALL popreal8(b(i))
      cb(i - 1) = cb(i - 1) - t * bb(i)
      CALL popreal8(t)
      tempb = tb / b(i - 1)
      ab(i) = ab(i) + tempb
      bb(i - 1) = bb(i - 1) - a(i) * tempb / b(i - 1)
    END DO
  END SUBROUTINE trdiag_b

    !!
!& ==============================================================================================================================
    !! SUBROUTINE   : trdiag
    !!
    !>\BRIEF        : Tridiagonal matrix algorithm solver using Thomas algorithm
    !!                solves Ax = g where A is a tridiagonal matrix consisting of vectors a, b, c
    !! DESCRIPTION : The Thomas algorithm, also known as the tridiagonal matrix algorithm,
    !!               is an efficient method for solving systems of linear equations with
    !!               a tridiagonal coefficient matrix.
    !!               n - number of equations
    !!               a - sub-diagonal (means it is the diagonal below the main diagonal)
    !!               b - the main diagonal
    !!               c - sup-diagonal (means it is the diagonal above the main diagonal)
    !!               g - right part
    !!               x - the answer
    !!
    !! RECENT CHANGE(S): None
    !!
    !! MAIN OUTPUT VARIABLE(S): Matrix of solutions x
    !!
    !! REFERENCE(S) : Joe D. Hoffman, 2001, Numerical Methods for Engineers and Scientists, Second Edition
    !!
    !! FLOWCHART    : None
    !_
    !&
!& ==============================================================================================================================
    !==
    SUBROUTINE trdiag(n, a, b, c, g, x)
    IMPLICIT NONE
    !! 0. Variables and parameter declaration
    !! 0.1 Input variables
    INTEGER, INTENT(IN) :: n
    REAL(KIND = r_std), DIMENSION(n), INTENT(IN) :: a
    REAL(KIND = r_std), DIMENSION(n), INTENT(IN) :: c
    !! 0.2 Output variables
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: x
    !! 0.3 Modified variables
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: b
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: g
    !! 0.4 Local variables
    INTEGER :: i
    REAL(KIND = r_std) :: t
    !_
    !&
!& ==============================================================================================================================
    !==
    ! Forward elimination phase
    DO i = 2, n
      t = a(i) / b(i - 1)
      b(i) = b(i) - c(i - 1) * t
      g(i) = g(i) - g(i - 1) * t
    END DO
    ! Backward substitution phase
    x(n) = g(n) / b(n)
    DO i = n - 1, 1, - 1
      x(i) = (g(i) - c(i) * x(i + 1)) / b(i)
    END DO
  END SUBROUTINE trdiag

END MODULE module_global_multilevel_matrixmodule_global_multilevel_matrix_adj
