!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 29 Jul 2025 17:17
!
! Global module for multilevel_matrix generated by fgpt
MODULE module_global_multilevel_matrixmodule_global_multilevel_matrix_tgt
  IMPLICIT NONE
  INTEGER, PARAMETER :: i_std = 4
  INTEGER, PARAMETER :: r_std = 8
  INTEGER(KIND = i_std), PARAMETER :: nice = 8
  INTEGER(KIND = i_std), PARAMETER :: ncirc = 3
  INTEGER(KIND = i_std), PARAMETER :: nsnow = 3
  INTEGER(KIND = i_std), PARAMETER :: nslm = 11
  INTEGER(KIND = i_std), PARAMETER :: nvm = 15
  INTEGER(KIND = i_std), PARAMETER :: nstm = 3
  INTEGER(KIND = i_std), PARAMETER :: kjpindex = 4717
  INTEGER :: ier
  INTEGER(KIND = i_std) :: ic0
  INTEGER(KIND = i_std) :: ic
  REAL(KIND = r_std) :: icr
  REAL(KIND = r_std) :: start_time
  REAL(KIND = r_std) :: stop_time
  INTEGER(KIND = i_std) :: nlevels_tot

  CONTAINS
  !  Differentiation of multilevel_matrix in forward (tangent) mode:
    !   variations   of useful results: fab fdn fup
    !   with respect to varying inputs: d t w fdn rs fup mu
    !   RW status of diff variables: d:in t:in w:in fab:out fdn:in-out
    !                rs:in fup:in-out mu:in
    !!
!& ==============================================================================================================================
    !! SUBROUTINE   : multilevel_matrix
    !!
    !>\BRIEF        : Multilevel matrix radiation transfer
    !!
    !! DESCRIPTION : Matrix radiation transfer where the mathematical representation
    !!               of radiative transfer involves using matrices to describe the transfer
    !!               of energy and properties of radiation within the medium.
    !!
    !! RECENT CHANGE(S): None
    !!
    !! MAIN OUTPUT VARIABLE(S): Upward flux, downward flux, and absorption
    !!
    !! REFERENCE(S) : K. Ardaneh et al. / Procedia Computer Science 255 (2025) 3–12
    !!
    !! FLOWCHART    :
    !! 1. Initialize Inputs
    !!
    !! Read vegetation canopy properties (LAI, reflectance, transmittance, scattering properties).
    !! Define incident solar flux, optical depth, and angular parameters.
    !! Set the number of layers nl.
    !!
    !! 2. Compute Two-Stream Coefficients
    !!
    !! Compute G(mu), K(mu), mu_bar, omega, omega_beta, and omega_beta0.
    !! Calculate two-stream approximation coefficients gamma1, gamma2, gamma3, gamma4.
    !!
    !! 3. Formulate the Matrix System
    !!
    !! Define the linear equations governing radiative transfer in multiple layers.
    !! Construct a tridiagonal system with coefficients e_l, d_l, f_l, g_l.
    !!
    !! 4. Apply Boundary Conditions
    !!
    !! At the top: Incoming downward flux.
    !! At the bottom: Upward flux determined by surface reflectance.
    !!
    !! 5. Solve Tridiagonal System
    !!
    !! Use the Thomas Algorithm for efficient computation.
    !! Compute flux amplitudes A_l, B_l for all layers.
    !!
    !! 6. Compute Final Radiative Fluxes
    !!
    !! Calculate downward and upward fluxes Fdn_l and Fup_l using solved amplitudes.
    !! Determine surface albedo, absorption (Fab), and transmission.
    !!
    !_
    !&
!& ==============================================================================================================================
    !==
    SUBROUTINE multilevel_matrix_d(nl, mu, mud, rs, rsd, t, td, w, wd, d, dd, fup, fupd, fdn, fdnd, fab, fabd)
    IMPLICIT NONE
    !! 0. Variables and parameter declaration
    !! 0.1 Input variables
    INTEGER, INTENT(IN) :: nl
    REAL(KIND = r_std), INTENT(IN) :: mu
    REAL(KIND = r_std), INTENT(IN) :: mud
    REAL(KIND = r_std), INTENT(IN) :: rs
    REAL(KIND = r_std), INTENT(IN) :: rsd
    REAL(KIND = r_std), INTENT(IN) :: w
    REAL(KIND = r_std), INTENT(IN) :: wd
    REAL(KIND = r_std), INTENT(IN) :: d
    REAL(KIND = r_std), INTENT(IN) :: dd
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(IN) :: t
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(IN) :: td
    !! 0.2 Output variables
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(INOUT) :: fup
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(INOUT) :: fupd
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(INOUT) :: fdn
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(INOUT) :: fdnd
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(OUT) :: fab
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(OUT) :: fabd
    !! 0.3 Modified variables
    !! 0.4 Local variables
    REAL(KIND = r_std), DIMENSION(nl * 2) :: xn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: xnd
    REAL(KIND = r_std), DIMENSION(nl * 2) :: an
    REAL(KIND = r_std), DIMENSION(nl * 2) :: and
    REAL(KIND = r_std), DIMENSION(nl * 2) :: bn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: bnd
    REAL(KIND = r_std), DIMENSION(nl * 2) :: cn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: cnd
    REAL(KIND = r_std), DIMENSION(nl * 2) :: gn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: gnd
    REAL(KIND = r_std), DIMENSION(2, nlevels_tot) :: data_pu
    REAL(KIND = r_std), DIMENSION(2, nlevels_tot) :: data_pud
    REAL(KIND = r_std), DIMENSION(11, nl) :: data_nl
    REAL(KIND = r_std), DIMENSION(11, nl) :: data_nld
    REAL(KIND = r_std), DIMENSION(4) :: gam
    REAL(KIND = r_std), DIMENSION(4) :: gamd
    REAL(KIND = r_std), PARAMETER :: g = 0.5_r_std
    REAL(KIND = r_std), PARAMETER :: mubar = 1.0_r_std
    REAL(KIND = r_std) :: bs
    REAL(KIND = r_std) :: bsd
    REAL(KIND = r_std) :: lambda
    REAL(KIND = r_std) :: lambdad
    REAL(KIND = r_std) :: cap_gam
    REAL(KIND = r_std) :: cap_gamd
    REAL(KIND = r_std) :: exp_trm
    REAL(KIND = r_std) :: exp_trmd
    REAL(KIND = r_std) :: cpn
    REAL(KIND = r_std) :: cpnd
    REAL(KIND = r_std) :: cmn
    REAL(KIND = r_std) :: cmnd
    REAL(KIND = r_std) :: den
    REAL(KIND = r_std) :: dend
    REAL(KIND = r_std) :: exp_top
    REAL(KIND = r_std) :: exp_topd
    REAL(KIND = r_std) :: exp_bot
    REAL(KIND = r_std) :: exp_botd
    REAL(KIND = r_std) :: fdu
    REAL(KIND = r_std) :: fdud
    REAL(KIND = r_std) :: fdb
    REAL(KIND = r_std) :: fdbd
    INTEGER :: l
    INTEGER :: le
    INTEGER :: lo
    REAL(KIND = r_std) :: fspi
    REAL(KIND = r_std) :: fspid
    REAL(KIND = r_std) :: mu0
    REAL(KIND = r_std) :: mu0d
    REAL(KIND = r_std) :: k
    REAL(KIND = r_std) :: kd
    REAL(KIND = r_std) :: beta
    REAL(KIND = r_std) :: betad
    REAL(KIND = r_std) :: beta0
    REAL(KIND = r_std) :: beta0d
    INTRINSIC :: SQRT
    INTRINSIC :: MIN
    INTRINSIC :: EXP
    REAL(KIND = r_std) :: min1
    REAL(KIND = r_std) :: min1d
    REAL(KIND = r_std) :: min2
    REAL(KIND = r_std) :: min2d
    REAL(KIND = r_std) :: min3
    REAL(KIND = r_std) :: min3d
    REAL(KIND = r_std) :: arg1
    REAL(KIND = r_std) :: arg1d
    REAL(KIND = r_std) :: temp
    REAL(KIND = r_std) :: temp0
    !_
    !&
!& ==============================================================================================================================
    !==
    fab(:) = 0.0_r_std
    kd = - (g * mud / mu ** 2)
    k = g / mu
    ! K in Eq. (12)
    temp = (w + 2.0_r_std * d * mu / 3.0_r_std) / w
    beta0d = 0.5_r_std * ((1.0 - temp) * wd + 2.0_r_std * (mu * dd / 3.0_r_std + d * mud / 3.0_r_std)) / w
    beta0 = 0.5_r_std * temp
    ! β0 Eq. (12)
    temp = (w + d / 3.0_r_std) / w
    betad = 0.5_r_std * ((1.0 - temp) * wd + dd / 3.0_r_std) / w
    beta = 0.5_r_std * temp
    ! β in Eq. (12)
    ! Gamma coefficients (γ₁, γ₂, γ₃, and γ₄ = 1 − γ₃) according to the δ-methods
    gamd = 0.0_8
    gamd(1) = - ((1.0_r_std - beta) * wd - w * betad)
    gam(1) = 1.0_r_std - (1.0_r_std - beta) * w
    gamd(2) = beta * wd + w * betad
    gam(2) = w * beta
    gamd(3) = beta0d
    gam(3) = beta0
    gamd(4) = - gamd(3)
    gam(4) = 1.0_r_std - gam(3)
    ! Transformation of the two-stream equations for vegetation
    mu0d = - (kd / k ** 2)
    mu0 = 1.0_r_std / k
    fspid = - (mu0d / mu0 ** 2)
    fspi = 1.0_r_std / mu0
    data_nld = 0.0_8
    data_nld(1, :) = td(nl : 1 : - 1)
    data_nl(1, :) = t(nl : 1 : - 1)
    ! Δτₗ in Fig. 1
    arg1d = 2 * gam(1) * gamd(1) - 2 * gam(2) * gamd(2)
    arg1 = gam(1) ** 2 - gam(2) ** 2
    temp = SQRT(arg1)
    IF (arg1 .EQ. 0.0) THEN
      lambdad = 0.0_8
    ELSE
      lambdad = arg1d / (2.0 * temp)
    END IF
    lambda = temp
    ! λ in Eq. (3)
    temp = gam(2) / (gam(1) + lambda)
    cap_gamd = (gamd(2) - temp * (gamd(1) + lambdad)) / (gam(1) + lambda)
    cap_gam = temp
    ! Γ in Eq. (3)
    ! Cumulative optical depths (τc)
    data_pu(1, 1) = 0.0_r_std
    data_pud = 0.0_8
    DO l = 2, nlevels_tot
      data_pud(1, l) = data_pud(1, l - 1) + data_nld(1, l - 1)
      data_pu(1, l) = data_pu(1, l - 1) + data_nl(1, l - 1)
    END DO
    fdb = 0.0_r_std
    ! diffuse flux at top
    data_pud(2, 1) = fspi * mu0d + mu0 * fspid
    data_pu(2, 1) = mu0 * fspi
    ! direct flux at top
      DO l = 1, nl
      IF (lambda * data_nl(1, l) .GT. 30.0_r_std) THEN
        min1 = 30.0_r_std
        min1d = 0.0_8
      ELSE
        min1d = data_nl(1, l) * lambdad + lambda * data_nld(1, l)
        min1 = lambda * data_nl(1, l)
      END IF
      ! Eqs. (8)
      exp_trmd = - (EXP(- min1) * min1d)
      exp_trm = EXP(- min1)
      data_nld(2, l) = exp_trm * cap_gamd + cap_gam * exp_trmd
      data_nl(2, l) = 1.0_r_std + cap_gam * exp_trm
      data_nld(3, l) = - (exp_trm * cap_gamd + cap_gam * exp_trmd)
      data_nl(3, l) = 1.0_r_std - cap_gam * exp_trm
      data_nld(4, l) = cap_gamd + exp_trmd
      data_nl(4, l) = cap_gam + exp_trm
      data_nld(5, l) = cap_gamd - exp_trmd
      data_nl(5, l) = cap_gam - exp_trm
      ! Exponential terms in Eq. (3)
      temp = 1.0 / mu0
      temp0 = (gam(1) - temp) * gam(3) + gam(4) * gam(2)
      cpnd = temp0 * (fspi * wd + w * fspid) + w * fspi * (gam(3) * (gamd(1) + temp * mu0d / mu0) + (gam(1) - temp) * gamd(3) + &
&gam(2) * gamd(4) + gam(4) * gamd(2))
      cpn = w * fspi * temp0
      temp0 = 1.0 / mu0
      temp = (gam(1) + temp0) * gam(4) + gam(2) * gam(3)
      cmnd = temp * (fspi * wd + w * fspid) + w * fspi * (gam(4) * (gamd(1) - temp0 * mu0d / mu0) + (gam(1) + temp0) * gamd(4) + &
&gam(3) * gamd(2) + gam(2) * gamd(3))
      cmn = w * fspi * temp
      temp0 = 1.0 / (mu0 * mu0)
      dend = 2 * lambda * lambdad + temp0 * 2 * mu0d / mu0
      den = lambda * lambda - temp0
      IF (data_pu(1, l) / mu0 .GT. 30.0_r_std) THEN
        min2 = 30.0_r_std
        min2d = 0.0_8
      ELSE
        temp0 = data_pu(1, l) / mu0
        min2d = (data_pud(1, l) - temp0 * mu0d) / mu0
        min2 = temp0
      END IF
      exp_topd = - (EXP(- min2) * min2d)
      exp_top = EXP(- min2)
      IF (data_nl(1, l) / mu0 .GT. 30.0_r_std) THEN
        min3 = 30.0_r_std
        min3d = 0.0_8
      ELSE
        temp0 = data_nl(1, l) / mu0
        min3d = (data_nld(1, l) - temp0 * mu0d) / mu0
        min3 = temp0
      END IF
      temp0 = EXP(- min3)
      exp_botd = temp0 * exp_topd - exp_top * EXP(- min3) * min3d
      exp_bot = exp_top * temp0
      data_pud(2, l + 1) = exp_bot * (fspi * mu0d + mu0 * fspid) + mu0 * fspi * exp_botd
      data_pu(2, l + 1) = mu0 * fspi * exp_bot
      temp0 = exp_top * cpn / den
      data_nld(6, l) = (cpn * exp_topd + exp_top * cpnd - temp0 * dend) / den
      data_nl(6, l) = temp0
      temp0 = exp_bot * cpn / den
      data_nld(7, l) = (cpn * exp_botd + exp_bot * cpnd - temp0 * dend) / den
      data_nl(7, l) = temp0
      temp0 = exp_top * cmn / den
      data_nld(8, l) = (cmn * exp_topd + exp_top * cmnd - temp0 * dend) / den
      data_nl(8, l) = temp0
      temp0 = exp_bot * cmn / den
      data_nld(9, l) = (cmn * exp_botd + exp_bot * cmnd - temp0 * dend) / den
      data_nl(9, l) = temp0
    END DO
    ! Boundary conditions at the top  of the structure.
    bsd = data_pu(2, nlevels_tot) * rsd + rs * data_pud(2, nlevels_tot)
    bs = rs * data_pu(2, nlevels_tot)
    an(1) = 0.0_r_std
    bnd = 0.0_8
    bnd(1) = data_nld(2, 1)
    bn(1) = data_nl(2, 1)
    cnd = 0.0_8
    cnd(1) = - data_nld(3, 1)
    cn(1) = - data_nl(3, 1)
    gnd = 0.0_8
    gnd(1) = - data_nld(8, 1)
    gn(1) = fdb - data_nl(8, 1)
    and = 0.0_8
    ! Matrix of coefficients in Eqs. (9)
      DO l = 1, nl - 1
      le = 2 * l
      lo = 2 * l + 1
      and(le) = data_nl(2, l) * data_nld(3, l + 1) + data_nl(3, l + 1) * data_nld(2, l) - data_nl(4, l) * data_nld(5, l + 1) - &
&data_nl(5, l + 1) * data_nld(4, l)
      an(le) = data_nl(3, l + 1) * data_nl(2, l) - data_nl(5, l + 1) * data_nl(4, l)
      and(lo) = data_nl(4, l) * data_nld(3, l) + data_nl(3, l) * data_nld(4, l) - data_nl(2, l) * data_nld(5, l) - data_nl(5, l) * &
&data_nld(2, l)
      an(lo) = data_nl(3, l) * data_nl(4, l) - data_nl(5, l) * data_nl(2, l)
      bnd(le) = data_nl(3, l + 1) * data_nld(3, l) + data_nl(3, l) * data_nld(3, l + 1) - data_nl(5, l + 1) * data_nld(5, l) - &
&data_nl(5, l) * data_nld(5, l + 1)
      bn(le) = data_nl(3, l) * data_nl(3, l + 1) - data_nl(5, l) * data_nl(5, l + 1)
      bnd(lo) = data_nl(2, l + 1) * data_nld(2, l) + data_nl(2, l) * data_nld(2, l + 1) - data_nl(4, l + 1) * data_nld(4, l) - &
&data_nl(4, l) * data_nld(4, l + 1)
      bn(lo) = data_nl(2, l) * data_nl(2, l + 1) - data_nl(4, l) * data_nl(4, l + 1)
      cnd(le) = data_nl(5, l + 1) * data_nld(2, l + 1) + data_nl(2, l + 1) * data_nld(5, l + 1) - data_nl(4, l + 1) * data_nld(3, &
&l + 1) - data_nl(3, l + 1) * data_nld(4, l + 1)
      cn(le) = data_nl(2, l + 1) * data_nl(5, l + 1) - data_nl(3, l + 1) * data_nl(4, l + 1)
      cnd(lo) = data_nl(5, l + 1) * data_nld(4, l) + data_nl(4, l) * data_nld(5, l + 1) - data_nl(3, l + 1) * data_nld(2, l) - &
&data_nl(2, l) * data_nld(3, l + 1)
      cn(lo) = data_nl(4, l) * data_nl(5, l + 1) - data_nl(2, l) * data_nl(3, l + 1)
      temp0 = data_nl(6, l + 1) - data_nl(7, l)
      temp = data_nl(8, l + 1) - data_nl(9, l)
      gnd(le) = temp0 * data_nld(3, l + 1) + data_nl(3, l + 1) * (data_nld(6, l + 1) - data_nld(7, l)) - temp * data_nld(5, l + 1) &
&- data_nl(5, l + 1) * (data_nld(8, l + 1) - data_nld(9, l))
      gn(le) = data_nl(3, l + 1) * temp0 - data_nl(5, l + 1) * temp
      temp0 = data_nl(6, l + 1) - data_nl(7, l)
      temp = data_nl(9, l) - data_nl(8, l + 1)
      gnd(lo) = temp0 * data_nld(4, l) + data_nl(4, l) * (data_nld(6, l + 1) - data_nld(7, l)) + temp * data_nld(2, l) + &
&data_nl(2, l) * (data_nld(9, l) - data_nld(8, l + 1))
      gn(lo) = data_nl(4, l) * temp0 + data_nl(2, l) * temp
    END DO
    ! Boundary conditions at the bottom of the structure.
    l = 2 * nl
    and(l) = data_nld(2, nl) - data_nl(4, nl) * rsd - rs * data_nld(4, nl)
    an(l) = data_nl(2, nl) - rs * data_nl(4, nl)
    bnd(l) = data_nld(3, nl) - data_nl(5, nl) * rsd - rs * data_nld(5, nl)
    bn(l) = data_nl(3, nl) - rs * data_nl(5, nl)
    cnd(l) = 0.0_8
    cn(l) = 0.0_r_std
    gnd(l) = bsd - data_nld(7, nl) + data_nl(9, nl) * rsd + rs * data_nld(9, nl)
    gn(l) = bs - data_nl(7, nl) + rs * data_nl(9, nl)
    xnd = 0.0_8
    CALL trdiag_d(l, an, and, bn, bnd, cn, cnd, gn, gnd, xn, xnd)
    ! Matrix solutions unpacking
    data_nld(10, :) = xnd(1 : l : 2)
    data_nl(10, :) = xn(1 : l : 2)
    data_nld(11, :) = xnd(2 : l : 2)
    data_nl(11, :) = xn(2 : l : 2)
    ! Calculation of flux
    fdud = data_nl(4, 1) * data_nld(10, 1) + data_nl(10, 1) * data_nld(4, 1) - data_nl(5, 1) * data_nld(11, 1) - data_nl(11, 1) * &
&data_nld(5, 1) + data_nld(6, 1)
    fdu = data_nl(10, 1) * data_nl(4, 1) - data_nl(11, 1) * data_nl(5, 1) + data_nl(6, 1)
    fupd(nlevels_tot) = fdud
    fup(nlevels_tot) = fdu
    fdnd(nlevels_tot) = data_pud(2, 1)
    fdn(nlevels_tot) = fdb + data_pu(2, 1)
    DO l = 1, nl
      le = nlevels_tot - l
      fdud = data_nl(2, l) * data_nld(10, l) + data_nl(10, l) * data_nld(2, l) + data_nl(3, l) * data_nld(11, l) + data_nl(11, l) &
&* data_nld(3, l) + data_nld(7, l)
      fdu = data_nl(10, l) * data_nl(2, l) + data_nl(11, l) * data_nl(3, l) + data_nl(7, l)
      fupd(le) = fdud
      fup(le) = fdu
      fdbd = data_nl(4, l) * data_nld(10, l) + data_nl(10, l) * data_nld(4, l) + data_nl(5, l) * data_nld(11, l) + data_nl(11, l) &
&* data_nld(5, l) + data_nld(9, l)
      fdb = data_nl(10, l) * data_nl(4, l) + data_nl(11, l) * data_nl(5, l) + data_nl(9, l)
      fdnd(le) = fdbd + data_pud(2, l + 1)
      fdn(le) = fdb + data_pu(2, l + 1)
    END DO
    ! Calculation of absorption
    fabd = 0.0_8
    fabd(nl : 1 : - 1) = fdnd(nlevels_tot : 2 : - 1) - fupd(nlevels_tot : 2 : - 1) + fupd(nl : 1 : - 1) - fdnd(nl : 1 : - 1)
    fab(nl : 1 : - 1) = fdn(nlevels_tot : 2 : - 1) - fup(nlevels_tot : 2 : - 1) - (fdn(nl : 1 : - 1) - fup(nl : 1 : - 1))
  END SUBROUTINE multilevel_matrix_d

    !!
!& ==============================================================================================================================
    !! SUBROUTINE   : multilevel_matrix
    !!
    !>\BRIEF        : Multilevel matrix radiation transfer
    !!
    !! DESCRIPTION : Matrix radiation transfer where the mathematical representation
    !!               of radiative transfer involves using matrices to describe the transfer
    !!               of energy and properties of radiation within the medium.
    !!
    !! RECENT CHANGE(S): None
    !!
    !! MAIN OUTPUT VARIABLE(S): Upward flux, downward flux, and absorption
    !!
    !! REFERENCE(S) : K. Ardaneh et al. / Procedia Computer Science 255 (2025) 3–12
    !!
    !! FLOWCHART    :
    !! 1. Initialize Inputs
    !!
    !! Read vegetation canopy properties (LAI, reflectance, transmittance, scattering properties).
    !! Define incident solar flux, optical depth, and angular parameters.
    !! Set the number of layers nl.
    !!
    !! 2. Compute Two-Stream Coefficients
    !!
    !! Compute G(mu), K(mu), mu_bar, omega, omega_beta, and omega_beta0.
    !! Calculate two-stream approximation coefficients gamma1, gamma2, gamma3, gamma4.
    !!
    !! 3. Formulate the Matrix System
    !!
    !! Define the linear equations governing radiative transfer in multiple layers.
    !! Construct a tridiagonal system with coefficients e_l, d_l, f_l, g_l.
    !!
    !! 4. Apply Boundary Conditions
    !!
    !! At the top: Incoming downward flux.
    !! At the bottom: Upward flux determined by surface reflectance.
    !!
    !! 5. Solve Tridiagonal System
    !!
    !! Use the Thomas Algorithm for efficient computation.
    !! Compute flux amplitudes A_l, B_l for all layers.
    !!
    !! 6. Compute Final Radiative Fluxes
    !!
    !! Calculate downward and upward fluxes Fdn_l and Fup_l using solved amplitudes.
    !! Determine surface albedo, absorption (Fab), and transmission.
    !!
    !_
    !&
!& ==============================================================================================================================
    !==
    SUBROUTINE multilevel_matrix(nl, mu, rs, t, w, d, fup, fdn, fab)
    IMPLICIT NONE
    !! 0. Variables and parameter declaration
    !! 0.1 Input variables
    INTEGER, INTENT(IN) :: nl
    REAL(KIND = r_std), INTENT(IN) :: mu
    REAL(KIND = r_std), INTENT(IN) :: rs
    REAL(KIND = r_std), INTENT(IN) :: w
    REAL(KIND = r_std), INTENT(IN) :: d
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(IN) :: t
    !! 0.2 Output variables
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(INOUT) :: fup
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(INOUT) :: fdn
    REAL(KIND = r_std), DIMENSION(nlevels_tot), INTENT(OUT) :: fab
    !! 0.3 Modified variables
    !! 0.4 Local variables
    REAL(KIND = r_std), DIMENSION(nl * 2) :: xn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: an
    REAL(KIND = r_std), DIMENSION(nl * 2) :: bn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: cn
    REAL(KIND = r_std), DIMENSION(nl * 2) :: gn
    REAL(KIND = r_std), DIMENSION(2, nlevels_tot) :: data_pu
    REAL(KIND = r_std), DIMENSION(11, nl) :: data_nl
    REAL(KIND = r_std), DIMENSION(4) :: gam
    REAL(KIND = r_std), PARAMETER :: g = 0.5_r_std
    REAL(KIND = r_std), PARAMETER :: mubar = 1.0_r_std
    REAL(KIND = r_std) :: bs
    REAL(KIND = r_std) :: lambda
    REAL(KIND = r_std) :: cap_gam
    REAL(KIND = r_std) :: exp_trm
    REAL(KIND = r_std) :: cpn
    REAL(KIND = r_std) :: cmn
    REAL(KIND = r_std) :: den
    REAL(KIND = r_std) :: exp_top
    REAL(KIND = r_std) :: exp_bot
    REAL(KIND = r_std) :: fdu
    REAL(KIND = r_std) :: fdb
    INTEGER :: l
    INTEGER :: le
    INTEGER :: lo
    REAL(KIND = r_std) :: fspi
    REAL(KIND = r_std) :: mu0
    REAL(KIND = r_std) :: k
    REAL(KIND = r_std) :: beta
    REAL(KIND = r_std) :: beta0
    INTRINSIC :: SQRT
    INTRINSIC :: MIN
    INTRINSIC :: EXP
    REAL(KIND = r_std) :: min1
    REAL(KIND = r_std) :: min2
    REAL(KIND = r_std) :: min3
    REAL(KIND = r_std) :: arg1
    !_
    !&
!& ==============================================================================================================================
    !==
    fab(:) = 0.0_r_std
    k = g / mu
    ! K in Eq. (12)
    beta0 = 0.5_r_std / w * (w + 2.0_r_std * d * mu / 3.0_r_std)
    ! β0 Eq. (12)
    beta = 0.5_r_std / w * (w + d / 3.0_r_std)
    ! β in Eq. (12)
    ! Gamma coefficients (γ₁, γ₂, γ₃, and γ₄ = 1 − γ₃) according to the δ-methods
    gam(1) = 1.0_r_std - (1.0_r_std - beta) * w
    gam(2) = w * beta
    gam(3) = beta0
    gam(4) = 1.0_r_std - gam(3)
    ! Transformation of the two-stream equations for vegetation
    mu0 = 1.0_r_std / k
    fspi = 1.0_r_std / mu0
    data_nl(1, :) = t(nl : 1 : - 1)
    ! Δτₗ in Fig. 1
    arg1 = gam(1) ** 2 - gam(2) ** 2
    lambda = SQRT(arg1)
    ! λ in Eq. (3)
    cap_gam = gam(2) / (gam(1) + lambda)
    ! Γ in Eq. (3)
    ! Cumulative optical depths (τc)
    data_pu(1, 1) = 0.0_r_std
    DO l = 2, nlevels_tot
      data_pu(1, l) = data_pu(1, l - 1) + data_nl(1, l - 1)
    END DO
    fdb = 0.0_r_std
    ! diffuse flux at top
    data_pu(2, 1) = mu0 * fspi
    ! direct flux at top
      DO l = 1, nl
      IF (lambda * data_nl(1, l) .GT. 30.0_r_std) THEN
        min1 = 30.0_r_std
      ELSE
        min1 = lambda * data_nl(1, l)
      END IF
      ! Eqs. (8)
      exp_trm = EXP(- min1)
      data_nl(2, l) = 1.0_r_std + cap_gam * exp_trm
      data_nl(3, l) = 1.0_r_std - cap_gam * exp_trm
      data_nl(4, l) = cap_gam + exp_trm
      data_nl(5, l) = cap_gam - exp_trm
      ! Exponential terms in Eq. (3)
      cpn = w * fspi * ((gam(1) - 1.0_r_std / mu0) * gam(3) + gam(4) * gam(2))
      cmn = w * fspi * ((gam(1) + 1.0_r_std / mu0) * gam(4) + gam(2) * gam(3))
      den = lambda ** 2 - 1.0_r_std / mu0 ** 2
      IF (data_pu(1, l) / mu0 .GT. 30.0_r_std) THEN
        min2 = 30.0_r_std
      ELSE
        min2 = data_pu(1, l) / mu0
      END IF
      exp_top = EXP(- min2)
      IF (data_nl(1, l) / mu0 .GT. 30.0_r_std) THEN
        min3 = 30.0_r_std
      ELSE
        min3 = data_nl(1, l) / mu0
      END IF
      exp_bot = exp_top * EXP(- min3)
      data_pu(2, l + 1) = mu0 * fspi * exp_bot
      data_nl(6, l) = exp_top * cpn / den
      data_nl(7, l) = exp_bot * cpn / den
      data_nl(8, l) = exp_top * cmn / den
      data_nl(9, l) = exp_bot * cmn / den
    END DO
    ! Boundary conditions at the top  of the structure.
    bs = rs * data_pu(2, nlevels_tot)
    an(1) = 0.0_r_std
    bn(1) = data_nl(2, 1)
    cn(1) = - data_nl(3, 1)
    gn(1) = fdb - data_nl(8, 1)
    ! Matrix of coefficients in Eqs. (9)
      DO l = 1, nl - 1
      le = 2 * l
      lo = 2 * l + 1
      an(le) = data_nl(3, l + 1) * data_nl(2, l) - data_nl(5, l + 1) * data_nl(4, l)
      an(lo) = data_nl(3, l) * data_nl(4, l) - data_nl(5, l) * data_nl(2, l)
      bn(le) = data_nl(3, l) * data_nl(3, l + 1) - data_nl(5, l) * data_nl(5, l + 1)
      bn(lo) = data_nl(2, l) * data_nl(2, l + 1) - data_nl(4, l) * data_nl(4, l + 1)
      cn(le) = data_nl(2, l + 1) * data_nl(5, l + 1) - data_nl(3, l + 1) * data_nl(4, l + 1)
      cn(lo) = data_nl(4, l) * data_nl(5, l + 1) - data_nl(2, l) * data_nl(3, l + 1)
      gn(le) = data_nl(3, l + 1) * (data_nl(6, l + 1) - data_nl(7, l)) - data_nl(5, l + 1) * (data_nl(8, l + 1) - data_nl(9, l))
      gn(lo) = data_nl(4, l) * (data_nl(6, l + 1) - data_nl(7, l)) + data_nl(2, l) * (data_nl(9, l) - data_nl(8, l + 1))
    END DO
    ! Boundary conditions at the bottom of the structure.
    l = 2 * nl
    an(l) = data_nl(2, nl) - rs * data_nl(4, nl)
    bn(l) = data_nl(3, nl) - rs * data_nl(5, nl)
    cn(l) = 0.0_r_std
    gn(l) = bs - data_nl(7, nl) + rs * data_nl(9, nl)
    CALL trdiag(l, an, bn, cn, gn, xn)
    ! Matrix solutions unpacking
    data_nl(10, :) = xn(1 : l : 2)
    data_nl(11, :) = xn(2 : l : 2)
    ! Calculation of flux
    fdu = data_nl(10, 1) * data_nl(4, 1) - data_nl(11, 1) * data_nl(5, 1) + data_nl(6, 1)
    fup(nlevels_tot) = fdu
    fdn(nlevels_tot) = fdb + data_pu(2, 1)
    DO l = 1, nl
      le = nlevels_tot - l
      fdu = data_nl(10, l) * data_nl(2, l) + data_nl(11, l) * data_nl(3, l) + data_nl(7, l)
      fup(le) = fdu
      fdb = data_nl(10, l) * data_nl(4, l) + data_nl(11, l) * data_nl(5, l) + data_nl(9, l)
      fdn(le) = fdb + data_pu(2, l + 1)
    END DO
    ! Calculation of absorption
    fab(nl : 1 : - 1) = fdn(nlevels_tot : 2 : - 1) - fup(nlevels_tot : 2 : - 1) - (fdn(nl : 1 : - 1) - fup(nl : 1 : - 1))
  END SUBROUTINE multilevel_matrix

    !  Differentiation of trdiag in forward (tangent) mode:
    !   variations   of useful results: x
    !   with respect to varying inputs: g a b c
    !!
!& ==============================================================================================================================
    !! SUBROUTINE   : trdiag
    !!
    !>\BRIEF        : Tridiagonal matrix algorithm solver using Thomas algorithm
    !!                solves Ax = g where A is a tridiagonal matrix consisting of vectors a, b, c
    !! DESCRIPTION : The Thomas algorithm, also known as the tridiagonal matrix algorithm,
    !!               is an efficient method for solving systems of linear equations with
    !!               a tridiagonal coefficient matrix.
    !!               n - number of equations
    !!               a - sub-diagonal (means it is the diagonal below the main diagonal)
    !!               b - the main diagonal
    !!               c - sup-diagonal (means it is the diagonal above the main diagonal)
    !!               g - right part
    !!               x - the answer
    !!
    !! RECENT CHANGE(S): None
    !!
    !! MAIN OUTPUT VARIABLE(S): Matrix of solutions x
    !!
    !! REFERENCE(S) : Joe D. Hoffman, 2001, Numerical Methods for Engineers and Scientists, Second Edition
    !!
    !! FLOWCHART    : None
    !_
    !&
!& ==============================================================================================================================
    !==
    SUBROUTINE trdiag_d(n, a, ad, b, bd, c, cd, g, gd, x, xd)
    IMPLICIT NONE
    !! 0. Variables and parameter declaration
    !! 0.1 Input variables
    INTEGER, INTENT(IN) :: n
    REAL(KIND = r_std), DIMENSION(n), INTENT(IN) :: a
    REAL(KIND = r_std), DIMENSION(n), INTENT(IN) :: ad
    REAL(KIND = r_std), DIMENSION(n), INTENT(IN) :: c
    REAL(KIND = r_std), DIMENSION(n), INTENT(IN) :: cd
    !! 0.2 Output variables
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: x
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: xd
    !! 0.3 Modified variables
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: b
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: bd
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: g
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: gd
    !! 0.4 Local variables
    INTEGER :: i
    REAL(KIND = r_std) :: t
    REAL(KIND = r_std) :: td
    REAL(KIND = r_std) :: temp
    !_
    !&
!& ==============================================================================================================================
    !==
    ! Forward elimination phase
    DO i = 2, n
      temp = a(i) / b(i - 1)
      td = (ad(i) - temp * bd(i - 1)) / b(i - 1)
      t = temp
      bd(i) = bd(i) - t * cd(i - 1) - c(i - 1) * td
      b(i) = b(i) - c(i - 1) * t
      gd(i) = gd(i) - t * gd(i - 1) - g(i - 1) * td
      g(i) = g(i) - g(i - 1) * t
    END DO
    ! Backward substitution phase
    xd = 0.0_8
    temp = g(n) / b(n)
    xd(n) = (gd(n) - temp * bd(n)) / b(n)
    x(n) = temp
    DO i = n - 1, 1, - 1
      temp = (g(i) - c(i) * x(i + 1)) / b(i)
      xd(i) = (gd(i) - x(i + 1) * cd(i) - c(i) * xd(i + 1) - temp * bd(i)) / b(i)
      x(i) = temp
    END DO
  END SUBROUTINE trdiag_d

    !!
!& ==============================================================================================================================
    !! SUBROUTINE   : trdiag
    !!
    !>\BRIEF        : Tridiagonal matrix algorithm solver using Thomas algorithm
    !!                solves Ax = g where A is a tridiagonal matrix consisting of vectors a, b, c
    !! DESCRIPTION : The Thomas algorithm, also known as the tridiagonal matrix algorithm,
    !!               is an efficient method for solving systems of linear equations with
    !!               a tridiagonal coefficient matrix.
    !!               n - number of equations
    !!               a - sub-diagonal (means it is the diagonal below the main diagonal)
    !!               b - the main diagonal
    !!               c - sup-diagonal (means it is the diagonal above the main diagonal)
    !!               g - right part
    !!               x - the answer
    !!
    !! RECENT CHANGE(S): None
    !!
    !! MAIN OUTPUT VARIABLE(S): Matrix of solutions x
    !!
    !! REFERENCE(S) : Joe D. Hoffman, 2001, Numerical Methods for Engineers and Scientists, Second Edition
    !!
    !! FLOWCHART    : None
    !_
    !&
!& ==============================================================================================================================
    !==
    SUBROUTINE trdiag(n, a, b, c, g, x)
    IMPLICIT NONE
    !! 0. Variables and parameter declaration
    !! 0.1 Input variables
    INTEGER, INTENT(IN) :: n
    REAL(KIND = r_std), DIMENSION(n), INTENT(IN) :: a
    REAL(KIND = r_std), DIMENSION(n), INTENT(IN) :: c
    !! 0.2 Output variables
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: x
    !! 0.3 Modified variables
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: b
    REAL(KIND = r_std), DIMENSION(n), INTENT(INOUT) :: g
    !! 0.4 Local variables
    INTEGER :: i
    REAL(KIND = r_std) :: t
    !_
    !&
!& ==============================================================================================================================
    !==
    ! Forward elimination phase
    DO i = 2, n
      t = a(i) / b(i - 1)
      b(i) = b(i) - c(i - 1) * t
      g(i) = g(i) - g(i - 1) * t
    END DO
    ! Backward substitution phase
    x(n) = g(n) / b(n)
    DO i = n - 1, 1, - 1
      x(i) = (g(i) - c(i) * x(i + 1)) / b(i)
    END DO
  END SUBROUTINE trdiag

END MODULE module_global_multilevel_matrixmodule_global_multilevel_matrix_tgt
